import { injectHints } from './hint_utils.mjs';

const worldBatch5 = {
    "q-countries-1551": { "en": "The spiritual home of the Catholic Church.", "he": "המרכז הרוחני של הכנסייה הקתולית." },
    "q-countries-1552": { "en": "It starts with a C; not Sydney or Melbourne.", "he": "מתחילה ב-ק'; לא סידני או מלבורן." },
    "q-countries-1553": { "en": "The second-largest continent in the world.", "he": "היבשת השנייה בגודלה בעולם." },
    "q-countries-1554": { "en": "A city in Ontario.", "he": "עיר באונטריו." },
    "q-countries-1555": { "en": "A Nordic island nation.", "he": "מדינת אי נורדית." },
    "q-countries-1556": { "en": "A three-letter word rhymes with 'ten'.", "he": "מילה בת שלוש אותיות." },
    "q-london-1945": { "en": "It has 'Metropolitan' in the name.", "he": "יש לה את המילה 'מטרופולין' בשם." },
    "q-london-1946": { "en": "A king who had a very difficult relationship with Parliament.", "he": "מלך שהיה לו קשר קשה מאוד עם הפרלמנט." },
    "q-london-1947": { "en": "Think of a famous architect who also designed a university in London.", "he": "חשבו על אדריכל מפורסם שעיצב גם אוניברסיטה בלונדון." },
    "q-london-1948": { "en": "The oldest part of the fortress built by William the Conqueror.", "he": "החלק העתיק ביותר של המבצר שנבנה על ידי ויליאם הכובש." },
    "q-london-1949": { "en": "It shares a name with a famous park.", "he": "הוא חולק שם עם פארק מפורסם." },
    "q-london-1950": { "en": "White's is often cited.", "he": "מועדון 'וייטס' (White's) מוזכר לעיתים קרובות." },
    "q-london-1951": { "en": "A major cathedral in London.", "he": "קתדרלה מרכזית בלונדון." },
    "q-london-1952": { "en": "Jonathan's Coffee House.", "he": "בית הקפה של ג'ונתן (Jonathan's)." },
    "q-london-1953": { "en": "Samuel Johnson's famous observation.", "he": "התצפית המפורסמת של סמואל ג'ונסון." },
    "q-london-1954": { "en": "The early 1860s.", "he": "תחילת שנות ה-60 של המאה ה-19." },
    "q-london-1959": { "en": "Palace of Westminster.", "he": "ארמון וסטמינסטר." },
    "q-london-1960": { "en": "Think of the Prime Meridian.", "he": "חשבו על קו האורך אפס." },
    "q-london-1961": { "en": "It's in the West End.", "he": "זה בווסט אנד." },
    "q-london-1962": { "en": "Mary Donaldson in 2023 was the most recent, but who was the first in 1983?", "he": "מרי דונלדסון הייתה לאחרונה, אבל מי הייתה הראשונה ב-1983?" },
    "q-london-1963": { "en": "Many professional offices are now there, but it was the heart of the press.", "he": "משרדים מקצועיים רבים נמצאים שם כיום, אך זה היה לב העיתונות." },
    "q-london-1964": { "en": "Temple Bar.", "he": "טמפל בר (Temple Bar)." },
    "q-london-1965": { "en": "St. James's Park or Hyde Park?", "he": "סנט ג'יימס פארק או הייד פארק?" },
    "q-london-1966": { "en": "A glass skyscraper designed by Renzo Piano.", "he": "גורד שחקים מזכוכית בעיצוב רנזו פיאנו." },
    "q-london-1967": { "en": "The Tate Modern.", "he": "הטייט מודרן." },
    "q-london-1968": { "en": "The Black Death's last major outbreak.", "he": "ההתפרצות הגדולה האחרונה של המוות השחור." },
    "q-london-1969": { "en": "A prominent Labour politician.", "he": "פוליטיקאי בכיר ממפלגת הלייבור." },
    "q-london-1970": { "en": "A green parsley sauce.", "he": "רוטב פטרוזיליה ירוק." },
    "q-london-1971": { "en": "J.M.W. Turner.", "he": "ג'.מ.וו. טרנר." },
    "q-london-1972": { "en": "Holland Park.", "he": "הולנד פארק." },
    "q-london-1973": { "en": "Highgate Cemetery.", "he": "בית הקברות הייגייט (Highgate)." },
    "q-london-1974": { "en": "The Millennium Bridge, due to a specific issue.", "he": "גשר המילניום, בשל בעיה ספציפית." },
    "q-london-1975": { "en": "The Temple.", "he": "הטמפל." },
    "q-london-1976": { "en": "Hampton Court Palace.", "he": "ארמון המפטון קורט." },
    "q-london-1977": { "en": "London Bridge is falling down.", "he": "גשר לונדון מתמוטט." },
    "q-london-2430": { "en": "Officially, a very small number, but likely much higher.", "he": "באופן רשמי מספר קטן מאוד, אך כנראה גבוה בהרבה." },
    "q-london-2431": { "en": "Dieu et mon droit.", "he": "אלוהים וזכותי (Dieu et mon droit)." },
    "q-london-2432": { "en": "Francis Fowke.", "he": "פרנסיס פוקה (Francis Fowke)." },
    "q-london-2433": { "en": "A royal palace and fortress.", "he": "ארמון מלכותי ומבצר." },
    "q-london-2434": { "en": "Westminster Abbey.", "he": "מנזר וסטמינסטר." },
    "q-london-2435": { "en": "The same as the execute king year, reversed?", "he": "באותה מאה של השריפה הגדולה." },
    "q-london-2436": { "en": "Tower Bridge.", "he": "גשר טאוור." },
    "q-london-2437": { "en": "London Bridge.", "he": "גשר לונדון." },
    "q-london-2438": { "en": "Prince of Wales.", "he": "נסיך ויילס." },
    "q-london-2439": { "en": "The Earl Marshal.", "he": "הארל מרשל (Earl Marshal)." },
    "q-london-2440": { "en": "Over 11,000.", "he": "מעל 11,000." },
    "q-london-2441": { "en": "The Tyburn.", "he": "הטייברן (Tyburn)." },
    "q-london-2442": { "en": "A special tax or duty.", "he": "מס או היטל מיוחד." },
    "q-london-2443": { "en": "Charles Barry.", "he": "צ'ארלס בארי." },
    "q-london-2444": { "en": "Holyroodhouse.", "he": "הולירודהאוס (Holyroodhouse)." },
    "q-london-2445": { "en": "The Northern Line.", "he": "קו נורת'רן (Northern)." },
    "q-london-2446": { "en": "A ceremony involving the keys of the Tower.", "he": "טקס הכולל את מפתחות המצודה." },
    "q-london-2447": { "en": "Around 30.", "he": "בסביבות 30." },
    "q-london-2448": { "en": "Waterloo Bridge.", "he": "גשר ווטרלו." },
    "q-london-2449": { "en": "Baltic Exchange.", "he": "הבורסה הבלטית (Baltic Exchange)." },
    "q-london-2450": { "en": "Same place as the previous question.", "he": "אותו מקום כמו בשאלה הקודמת." },
    "q-london-2481": { "en": "All Hallows-by-the-Tower.", "he": "אול הלוז-על-יד-המצודה." },
    "q-london-2482": { "en": "Sir Christopher Wren.", "he": "סר כריסטופר רן." },
    "q-london-2483": { "en": "A garden or a sewer?", "he": "גן או תעלת ביוב?" },
    "q-london-2484": { "en": "Queen Victoria.", "he": "המלכה ויקטוריה." },
    "q-london-2485": { "en": "122 Leadenhall Street.", "he": "רחוב לידנהול 122." },
    "q-london-2486": { "en": "1665.", "he": "1665." },
    "q-london-2487": { "en": "Lord Rogers.", "he": "לורד רוג'רס." },
    "q-london-2488": { "en": "Colonel Blood.", "he": "קולונל בלאד (Colonel Blood)." },
    "q-london-2489": { "en": "A partisan or halberd.", "he": "פרטיזן או הלברד." },
    "q-london-2490": { "en": "One year.", "he": "שנה אחת." },
    "q-london-2491": { "en": "The Walkie-Talkie.", "he": "הווקי-טוקי." },
    "q-london-2492": { "en": "Mount Pleasant.", "he": "מאונט פלזנט (Mount Pleasant)." },
    "q-london-2493": { "en": "Queen Victoria.", "he": "המלכה ויקטוריה." },
    "q-london-2494": { "en": "Ceremonial boundaries.", "he": "גבולות טקסיים." },
    "q-london-2495": { "en": "Metropolitan Police Service.", "he": "שירות המשטרה המטרופוליטני." },
    "q-london-2496": { "en": "1851.", "he": "1851." },
    "q-london-2497": { "en": "Geoffrey Chaucer.", "he": "ג'ופרי צ'וסר." },
    "q-london-2498": { "en": "It was used for sensitive communications.", "he": "הוא שימש לתקשורת רגישה." },
    "q-london-2499": { "en": "The Gold State Coach.", "he": "מרכבת המדינה המוזהבת." },
    "q-london-2500": { "en": "Kensington Palace.", "he": "ארמון קנזינגטון." },
    "q-countries-3081": { "en": "Lima.", "he": "לימה." },
    "q-countries-3082": { "en": "Wellington.", "he": "וולינגטון." },
    "q-countries-3083": { "en": "Hanoi.", "he": "האנוי." },
    "q-countries-3084": { "en": "Nairobi.", "he": "ניירובי." },
    "q-countries-3085": { "en": "Stockholm.", "he": "שטוקהולם." },
    "q-countries-3086": { "en": "Oslo.", "he": "אוסלו." },
    "q-countries-3087": { "en": "Bogotá.", "he": "בוגוטה." },
    "q-countries-3088": { "en": "Lisbon.", "he": "ליסבון." },
    "q-countries-3089": { "en": "Rabat.", "he": "רבאט." },
    "q-countries-3090": { "en": "Seoul.", "he": "סיאול." },
    "q-countries-3136": { "en": "Peru.", "he": "פרו." },
    "q-countries-3137": { "en": "New Zealand.", "he": "ניו זילנד." },
    "q-countries-3138": { "en": "Vietnam.", "he": "וייטנאם." },
    "q-countries-3139": { "en": "Kenya.", "he": "קניה." },
    "q-countries-3140": { "en": "Sweden.", "he": "שוודיה." },
    "q-countries-3176": { "en": "The Grand Canyon.", "he": "הגרנד קניון." },
    "q-countries-3177": { "en": "Statue of Liberty.", "he": "פסל החירות." },
    "q-countries-3178": { "en": "Mount Rushmore.", "he": "הר ראשמור." },
    "q-countries-3179": { "en": "The Golden Gate Bridge.", "he": "גשר הזהב." },
    "q-countries-3180": { "en": "Central Park.", "he": "סנטרל פארק." },
    "q-countries-3181": { "en": "The White House.", "he": "הבית הלבן." },
    "q-countries-3182": { "en": "Arlington National Cemetery.", "he": "בית הקברות הלאומי ארלינגטון." },
    "q-countries-3183": { "en": "Yellowstone National Park.", "he": "הפארק הלאומי ילוסטון." },
    "q-countries-3184": { "en": "Yosemite National Park.", "he": "הפארק הלאומי יוסמיטי." }
};

injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/world.js', worldBatch5);
