import { injectHints } from './hint_utils.mjs';

const sportsBatch4 = {
    "q-maccabi_haifa-336": { "en": "The club was founded early in the 20th century.", "he": "המועדון נוסד בתחילת המאה ה-20." },
    "q-maccabi_haifa-337": { "en": "A team from Turin, Italy.", "he": "קבוצה מטורינו, איטליה." },
    "q-maccabi_haifa-338": { "en": "A French midfielder who became a Haifa legend.", "he": "קשר צרפתי שהפך לאגדה בחיפה." },
    "q-maccabi_haifa-339": { "en": "His name starts with A and ends with u.", "he": "שמו מתחיל ב-א' ומסתיים ב-ו'." },
    "q-maccabi_haifa-340": { "en": "A high-scoring game ending with a 5 in it.", "he": "משחק רב שערים שנגמר עם 5." },
    "q-maccabi_haifa-341": { "en": "A legendary defender whose last name is Benado.", "he": "בלם אגדי ששם משפחתו בנאדו." },
    "q-maccabi_haifa-342": { "en": "He scored a late, dramatic goal.", "he": "הוא כבש שער מאוחר ודרמטי." },
    "q-maccabi_haifa-343": { "en": "He came from the MLS.", "he": "הוא הגיע מה-MLS." },
    "q-maccabi_haifa-344": { "en": "A very large margin, double digits locally.", "he": "פער גדול מאוד, מספר דו-ספרתי מקומי." },
    "q-maccabi_haifa-345": { "en": "It's more than 40 games.", "he": "זה מעל 40 משחקים." },
    "q-maccabi_haifa-346": { "en": "It's around 30,000.", "he": "זה בסביבות ה-30,000." },
    "q-maccabi_haifa-347": { "en": "A midfielder known for his powerful shots.", "he": "קשר הידוע בבעיטות העוצמתיות שלו." },
    "q-maccabi_haifa-348": { "en": "A team from Tel Aviv, but not Maccabi.", "he": "קבוצה מתל אביב, אבל לא מכבי." },
    "q-maccabi_haifa-349": { "en": "A now-defunct European cup.", "he": "גביע אירופי שכבר לא קיים." },
    "q-maccabi_haifa-350": { "en": "He coached the Israeli national team later.", "he": "הוא אימן את נבחרת ישראל מאוחר יותר." },
    "q-maccabi_haifa-351": { "en": "A famous businessman whose name is Ya'akov.", "he": "איש עסקים מפורסם ששמו יעקב." },
    "q-maccabi_haifa-352": { "en": "A double-digit number of consecutive wins.", "he": "מספר דו-ספרתי של ניצחונות רצופים." },
    "q-maccabi_haifa-353": { "en": "A creative midfielder from the 60s.", "he": "קשר יצירתי משנות ה-60." },
    "q-maccabi_haifa-354": { "en": "A striker from the former Soviet Union.", "he": "חלוץ מברית המועצות לשעבר." },
    "q-maccabi_haifa-381": { "en": "The answer is Juventus.", "he": "התשובה היא יובנטוס." },
    "q-maccabi_haifa-382": { "en": "A team with a very small name, also from Tel Aviv.", "he": "קבוצה עם שם קטן מאוד, גם מתל אביב." },
    "q-maccabi_haifa-383": { "en": "Maccabi Tel Aviv was the opponent.", "he": "מכבי תל אביב הייתה היריבה." },
    "q-maccabi_haifa-405": { "en": "Yes, it was their first major title.", "he": "כן, זה היה התואר המשמעותי הראשון שלהם." },
    "q-maccabi_haifa-406": { "en": "Yes, they won it in the early 90s.", "he": "כן, הם זכו בו בתחילת שנות ה-90." },
    "q-maccabi_haifa-407": { "en": "Yes, their winning streak continued.", "he": "כן, רצף הזכיות שלהם נמשך." },
    "q-maccabi_haifa-408": { "en": "Yes, another cup in the mid-90s.", "he": "כן, עוד גביע באמצע שנות ה-90." },
    "q-maccabi_haifa-409": { "en": "Yes, a famous year for the club.", "he": "כן, שנה מפורסמת למועדון." },
    "q-maccabi_haifa-410": { "en": "Yes, after a long drought.", "he": "כן, אחרי בצורת ארוכה." },
    "q-maccabi_haifa-411": { "en": "Search for 'Maccabi Netanya'.", "he": "חפשו את 'מכבי נתניה'." },
    "q-maccabi_haifa-412": { "en": "The opponent was Hapoel Tel Aviv.", "he": "היריבה הייתה הפועל תל אביב." },
    "q-maccabi_haifa-413": { "en": "Beitar Tel Aviv was the team.", "he": "ביתר תל אביב הייתה הקבוצה." },
    "q-maccabi_haifa-414": { "en": "A very high points total, near 100.", "he": "סך נקודות גבוה מאוד, קרוב ל-100." },
    "q-maccabi_haifa-415": { "en": "It's around 97 goals.", "he": "זה בסביבות ה-97 שערים." },
    "q-maccabi_haifa-416": { "en": "A number between 40 and 50.", "he": "מספר בין 40 ל-50." },
    "q-maccabi_haifa-417": { "en": "A number between 20 and 30.", "he": "מספר בין 20 ל-30." },
    "q-maccabi_haifa-418": { "en": "Maccabi Tel Aviv at the Ramat Gan Stadium.", "he": "מכבי תל אביב באצטדיון רמת גן." },
    "q-maccabi_haifa-419": { "en": "Against Manchester United/Olympiacos at Old Trafford.", "he": "נגד מנצ'סטר יונייטד/אולימפיאקוס באולד טראפורד." },
    "q-maccabi_haifa-420": { "en": "A very small triple-digit number.", "he": "מספר תלת-ספרתי קטן מאוד." },
    "q-maccabi_haifa-423": { "en": "His first name is Nir.", "he": "שמו הפרטי הוא ניר." },
    "q-maccabi_haifa-424": { "en": "A midfielder whose name is Yaniv.", "he": "קשר ששמו יניב." },
    "q-maccabi_haifa-425": { "en": "His name rhymes with 'hat'.", "he": "שמו מתחרז עם 'קאת'." },
    "q-maccabi_haifa-426": { "en": "Yakubu was the first foreigner, but who was the first Israeli?", "he": "יעקובו היה הזר הראשון, אבל מי היה הישראלי הראשון?" },
    "q-maccabi_haifa-427": { "en": "A player with the last name Buanani.", "he": "שחקן עם שם המשפחה בואנני." },
    "q-maccabi_haifa-428": { "en": "A team named Hapoel Tayibe.", "he": "קבוצה בשם הפועל טייבה." },
    "q-maccabi_haifa-429": { "en": "It was in the mid-80s.", "he": "זה היה באמצע שנות ה-80." },
    "q-maccabi_haifa-430": { "en": "Hapoel Jerusalem was the opponent.", "he": "הפועל ירושלים הייתה היריבה." },
    "q-maccabi_haifa-432": { "en": "Yes, their first title.", "he": "כן, האליפות הראשונה שלהם." },
    "q-maccabi_haifa-434": { "en": "Yes, the back-to-back win.", "he": "כן, הזכייה השנייה ברציפות." },
    "q-maccabi_haifa-436": { "en": "Yes, the late 80s success.", "he": "כן, ההצלחה בסוף שנות ה-80." },
    "q-maccabi_haifa-438": { "en": "Yes, the double year.", "he": "כן, שנת הדאבל." },
    "q-maccabi_haifa-440": { "en": "Yes, the unbeaten season.", "he": "כן, העונה ללא הפסד." },
    "q-maccabi_haifa-442": { "en": "Yes, under Avram Grant.", "he": "כן, תחת אברהם גרנט." },
    "q-maccabi_haifa-444": { "en": "Yes, back-to-back under Grant.", "he": "כן, אליפות שנייה ברציפות תחת גרנט." },
    "q-maccabi_haifa-446": { "en": "Yes, under Roni Levy.", "he": "כן, תחת רוני לוי." },
    "q-maccabi_haifa-448": { "en": "Yes, the second under Roni Levy.", "he": "כן, השנייה תחת רוני לוי." },
    "q-maccabi_haifa-450": { "en": "Yes, the third in a row under Roni Levy.", "he": "כן, השלישית ברציפות תחת רוני לוי." },
    "q-maccabi_haifa-452": { "en": "Yes, after a short gap.", "he": "כן, אחרי הפסקה קצרה." },
    "q-maccabi_haifa-454": { "en": "Yes, with Elisha Levy.", "he": "כן, עם אלישע לוי." },
    "q-maccabi_haifa-456": { "en": "Yes, breaking the drought with Bakhar.", "he": "כן, שבירת הבצורת עם בכר." },
    "q-maccabi_haifa-458": { "en": "Yes, consecutive titles with Bakhar.", "he": "כן, אליפות שנייה ברציפות עם בכר." },
    "q-maccabi_haifa-460": { "en": "Yes, the three-peat with Bakhar.", "he": "כן, האליפות השלישית ברציפות עם בכר." },
    "q-maccabi_haifa-461": { "en": "Yes, it is the official count.", "he": "כן, זה המניין הרשמי." },
    "q-maccabi_haifa-462": { "en": "Yes, the count is correct.", "he": "כן, המניין נכון." },
    "q-maccabi_haifa-463": { "en": "Yes, true information.", "he": "כן, מידע נכון." },
    "q-maccabi_haifa-464": { "en": "Yes, confirmed records.", "he": "כן, רשומות מאושרות." },
    "q-patisserie-965": { "en": "It strengthens the gluten structure.", "he": "זה מחזק את מבנה הגלוטן." },
    "q-patisserie-966": { "en": "It is an acid.", "he": "זוהי חומצה." },
    "q-patisserie-967": { "en": "Cooking continue after removal from heat.", "he": "הבישול ממשיך לאחר ההסרה מהאש." },
    "q-patisserie-968": { "en": "The starch granules swell and absorb water.", "he": "גרגרי העמילן מתנפחים וסופגים מים." },
    "q-patisserie-969": { "en": "It contains emulsifiers to hold more liquid and sugar.", "he": "זה מכיל מתחלבים כדי להחזיק יותר נוזלים וסוכר." },
    "q-patisserie-971": { "en": "To prevent the dough from rising too much or blistering.", "he": "כדי למנוע מהבצק לתפוח יותר מדי או ליצור בועות." },
    "q-patisserie-972": { "en": "Mixing fat into flour to create a sandy texture.", "he": "ערבוב שומן לתוך קמח ליצירת מרקם חולי." },
    "q-patisserie-974": { "en": "A glaze used to give pastries a shiny finish.", "he": "זיגוג המשמש למתן גימור מבריק למאפים." },
    "q-patisserie-975": { "en": "Almond sponge, buttercream, and ganache.", "he": "ספוג שקדים, קרם חמאה וגנאש." },
    "q-patisserie-977": { "en": "The sisters who owned the hotel where it was invented.", "he": "האחיות שהיו בבעלותן המלון בו הוא הומצא." },
    "q-patisserie-979": { "en": "Galette des Rois.", "he": "גאלט דה רואה (Galette des Rois)." },
    "q-patisserie-981": { "en": "Ground almonds and sugar.", "he": "שקדים טחונים וסוכר." },
    "q-patisserie-982": { "en": "A moist, unrefined brown sugar with plenty of molasses.", "he": "סוכר חום לח ולא מזוקק עם הרבה מולסה." },
    "q-patisserie-984": { "en": "An almond-flavored pastry cream.", "he": "קרם מאפה בטעם שקדים." },
    "q-patisserie-985": { "en": "The ability to attract and hold water molecules.", "he": "היכולת למשוך ולהחזיק מולקולות מים." },
    "q-patisserie-986": { "en": "A temperature range where sugar forms a flexible ball in cold water.", "he": "טווח טמפרטורות בו הסוכר יוצר כדור גמיש במים קרים." },
    "q-patisserie-987": { "en": "A mixture of glucose and fructose that prevents crystallization.", "he": "תערובת של גלוקוז ופרוקטוז המונעת התגבשות." },
    "q-patisserie-988": { "en": "A reaction involving polyphenol oxidase.", "he": "תגובה הכוללת פוליפנול אוקסידאז." },
    "q-patisserie-989": { "en": "To provide elasticity and structure in the absence of gluten.", "he": "לספק אלסטיות ומבנה בהיעדר גלוטן." },
    "q-patisserie-991": { "en": "Gelatin is animal-based; Agar is plant-based.", "he": "ג'לטין מבוסס מן החי; אגר מבוסס מן הצומח." },
    "q-patisserie-992": { "en": "Slowly adding hot liquid to eggs to raise their temperature without scrambling.", "he": "הוספה איטית של נוזל חם לביצים כדי להעלות את הטמפרטורה שלהן בלי לבשל אותן." },
    "q-patisserie-993": { "en": "Whisked egg yolks and sugar syrup.", "he": "חלמונים מוקצפים וסירופ סוכר." },
    "q-patisserie-994": { "en": "Pastry cream mixed with whipped cream and gelatin.", "he": "קרם פטיסייר מעורבב עם קצפת וג'לטין." },
    "q-patisserie-996": { "en": "It acts as an emulsifier to reduce viscosity.", "he": "הוא משמש כמתחלב להפחתת הצמיגות." },
    "q-patisserie-997": { "en": "Fat or sugar crystals rising to the surface.", "he": "גבישי שומן או סוכר שעולים על פני השטח." },
    "q-patisserie-998": { "en": "It originated from the Austrian Kipferl.", "he": "הוא מקורו בקיפרל (Kipferl) האוסטרי." },
    "q-patisserie-999": { "en": "A small French pastry with a custard center and caramelized crust.", "he": "מאפה צרפתי קטן עם מרכז קרמי וקרום מקורמל." },
    "q-patisserie-1001": { "en": "Shortcrust pastry (Pâte Brisée).", "he": "בצק פריך (Pâte Brisée)." },
    "q-patisserie-1002": { "en": "A crumbly topping made of flour, butter, and sugar.", "he": "תוספת פירורית העשויה מקמח, חמאה וסוכר." },
    "q-patisserie-1003": { "en": "A mixture of nuts and caramelized sugar.", "he": "תערובת של אגוזים וסוכר מקורמל." },
    "q-patisserie-1004": { "en": "A sponge cake made by whisking whole eggs with sugar over heat.", "he": "עוגת ספוג המוכנת על ידי הקצפת ביצים שלמות עם סוכר מעל חום." },
    "q-patisserie-1010": { "en": "To ensure stability, shine, and a proper snap.", "he": "כדי להבטיח יציבות, ברק ושבירה נכונה." },
    "q-patisserie-1012": { "en": "To preserve the air bubbles incorporated during whisking.", "he": "כדי לשמר את בועות האוויר שנוצרו בזמן ההקצפה." },
    "q-patisserie-1017": { "en": "To keep the fat solid for a flaky texture.", "he": "כדי לשמור על השומן מוצק למרקם פתיתי." },
    "q-patisserie-1020": { "en": "The sugar might crystallize.", "he": "הסוכר עלול להתגבש." }
};

injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/sports_life.js', sportsBatch4);
