import { injectHints } from './hint_utils.mjs';

const israelBatch8 = {
    "israel_geo_exist_21": { "en": "Look for a name that sounds like a familiar Israeli city.", "he": "חפשו שם שנשמע כמו שם של עיר ישראלית מוכרת." },
    "israel_geo_exist_32": { "en": "One of these is a real town, others are made up.", "he": "אחד מהם הוא יישוב אמיתי, האחרים מומצאים." },
    "israel_geo_exist_24": { "en": "This place is a real town in Israel.", "he": "המקום הזה הוא יישוב אמיתי בישראל." },
    "israel_geo_exist_40": { "en": "Focus on the name that sounds logically connected to Israeli geography.", "he": "התמקדו בשם שנשמע מחובר גאוגרפית לישראל." },
    "israel_geo_fact_year_111": { "en": "It was founded in the early 20th century, around 1907.", "he": "הוא נוסד בתחילת המאה ה-20, בסביבות 1907." },
    "israel_geo_exist_53": { "en": "Think of a name you've seen on a map of Israel.", "he": "חשבו על שם שראיתם פעם על מפת ישראל." },
    "israel_geo_exist_5": { "en": "Which one sounds like a real Israeli community?", "he": "איזה מהם נשמע כמו יישוב ישראלי אמיתי?" },
    "israel_geo_exist_28": { "en": "Only one of these options is a real place.", "he": "רק אחת מהאפשרויות היא מקום אמיתי." },
    "israel_geo_exist_51": { "en": "Scan the names for a real Israeli town.", "he": "חפשו בין השמות עיר או יישוב אמיתי." },
    "israel_geo_exist_16": { "en": "Identify the real city name.", "he": "זהו את השם של העיר האמיתית." },
    "israel_geo_exist_14": { "en": "One of these is definitely on the map.", "he": "אחד מהם נמצא בוודאות על המפה." },
    "israel_geo_exist_31": { "en": "Which one is a real Israeli settlement?", "he": "איזה מהם הוא יישוב ישראלי אמיתי?" },
    "israel_geo_fact_year_50": { "en": "This historic lower Galilee colony was founded in 1902.", "he": "המושבה ההיסטורית הזו בגליל התחתון נוסדה ב-1902." },
    "israel_geo_exist_6": { "en": "Look for the name of a real kibbutz or city.", "he": "חפשו את שמו של קיבוץ או עיר אמיתיים." },
    "israel_geo_exist_34": { "en": "One is real, the rest are fake names.", "he": "אחד אמיתי, השאר שמות מזויפים." },
    "israel_geo_fact_year_47": { "en": "This kibbutz in the Hula Valley was founded in 1917.", "he": "הקיבוץ הזה בעמק החולה נוסד ב-1917." },
    "israel_geo_exist_48": { "en": "Which one do you recognize from the news or travel?", "he": "איזה מהם אתם מזהים מהחדשות או מטיול?" },
    "israel_geo_exist_58": { "en": "Pick the real town name.", "he": "בחרו בשם של היישוב האמיתי." },
    "israel_geo_exist_38": { "en": "Identify the genuine Israeli location.", "he": "זהו את המיקום הישראלי המקורי." },
    "israel_geo_exist_43": { "en": "Found the real name among the decoys.", "he": "מצאו את השם האמיתי בין השמות המסיחים." },
    "israel_geo_exist_27": { "en": "Which city is actually in Israel?", "he": "איזו עיר נמצאת באמת בישראל?" },
    "israel_geo_exist_3": { "en": "One of these is a real Israeli city.", "he": "אחת מהן היא עיר ישראלית אמיתית." },
    "israel_geo_exist_50": { "en": "Look for a familiar Israeli place name.", "he": "חפשו שם של מקום ישראלי מוכר." },
    "israel_geo_exist_9": { "en": "Which one is a real town?", "he": "איזה מהם הוא יישוב אמיתי?" },
    "israel_geo_exist_45": { "en": "Only one option is correct.", "he": "רק אפשרות אחת היא נכונה." },
    "israel_geo_exist_47": { "en": "Pick the real Israeli community.", "he": "בחרו בקהילה הישראלית האמיתית." },
    "israel_geo_exist_12": { "en": "Identify the real town.", "he": "זהו את היישוב האמיתי." },
    "israel_geo_exist_29": { "en": "One is real, three are fake.", "he": "אחד אמיתי, שלושה מזויפים." },
    "israel_geo_exist_26": { "en": "Look for a name on the map of Israel.", "he": "חפשו שם שמופיע במפת ישראל." },
    "israel_geo_exist_7": { "en": "Which one is a real city?", "he": "איזו מהן היא עיר אמיתית?" },
    "israel_geo_exist_18": { "en": "Identify the real location.", "he": "זהו את המיקום האמיתי." },
    "israel_geo_exist_35": { "en": "Pick the actual city name.", "he": "בחרו בשם העיר הממשי." },
    "q-tel-aviv-131": { "en": "It's named after a biblical shell or a type of fruit/field.", "he": "מדובר בשם של מגרש היסטורי, 'כרם' הוא חלק מהשם." },
    "q-tel-aviv-132": { "en": "World War I was raging in the region at the time.", "he": "מלחמת העולם הראשונה השתוללה באזור באותו זמן." },
    "q-tel-aviv-133": { "en": "A British architect known for his work in the Mandate era.", "he": "אדריכל בריטי המוכר מעבודותיו בתקופת המנדט." },
    "q-tel-aviv-134": { "en": "A beautiful white building in the French style on Rothschild Blvd.", "he": "בניין לבן ויפהפה בסגנון צרפתי בשדרות רוטשילד." },
    "q-tel-aviv-135": { "en": "A major event for the World Zionist Organization.", "he": "אירוע מרכזי של ההסתדרות הציונית העולמית." },
    "q-tel-aviv-138": { "en": "A Scottish biologist and town planner.", "he": "ביולוג ומתכנן ערים סקוטי." },
    "q-tel-aviv-139": { "en": "A famous Irgun ship that was the center of a major conflict.", "he": "אוניית אצ\"ל מפורסמת שהייתה במוקד של עימות קשה." },
    "q-patisserie-1021": { "en": "Check the oil temp.", "he": "בדקו את חום השמן." },
    "q-tel-aviv-140": { "en": "It's the area now known as 'Sarona'.", "he": "זהו האזור המוכר היום כ'שרונה'." },
    "q-tel-aviv-141": { "en": "A Jewish architect who emigrated from Poland.", "he": "אדריכל יהודי שעלה מפולין (יהודה מגידוביץ')." },
    "q-tel-aviv-142": { "en": "It was a medium-sized hall for its time, around 600-800 seats.", "he": "זה היה אולם בינוני לזמנו, בסביבות 600-800 מושבים." },
    "q-tel-aviv-143": { "en": "Shlomo Lahat (Chich) succeeded him.", "he": "שלמה להט (צ'יץ') החליף אותו." },
    "q-tel-aviv-144": { "en": "Named after a famous explorer or 'The Lighthouse'.", "he": "נקרא על שם מגלה ארצות מפורסם או 'המגדלור'." },
    "q-tel-aviv-145": { "en": "A famous poetess, often called 'Rachel' or something similar.", "he": "משוררת מפורסמת, לעתים נקראת 'רחל' או שם דומה." },
    "q-tel-aviv-146": { "en": "The 'Thermometer House' is one such example.", "he": "הוא לעתים מכונה 'בית המדחום'." },
    "q-tel-aviv-147": { "en": "It was originally called 'Carmel Street'.", "he": "במקור הוא נקרא 'רחוב הכרמל'." },
    "q-tel-aviv-148": { "en": "A famous Israeli artist like Nahum Gutman.", "he": "אמן ישראלי מפורסם כמו נחום גוטמן." },
    "q-tel-aviv-149": { "en": "It was held in the mid-1930s (1934 or 1932).", "he": "זה נערך באמצע שנות ה-30 (1932 או 1934)." },
    "q-tel-aviv-150": { "en": "Israel Rokach or a later mayor like Rabinowitz.", "he": "היה זה ראש העיר שלמה להט (צ'יץ')." },
    "q-tel-aviv-151": { "en": "They mainly came from Germany after 1933.", "he": "הם הגיעו בעיקר מגרמניה לאחר שנת 1933." },
    "q-tel-aviv-152": { "en": "The Herzliya Gymnasium stood there.", "he": "הגימנסיה הרצליה עמדה שם." },
    "q-tel-aviv-153": { "en": "The master plan for the development of Tel Aviv.", "he": "תכנית המתאר הכוללת לפיתוחה של תל אביב." },
    "q-tel-aviv-154": { "en": "A legendary composer like Sasha Argov.", "he": "מלחין אגדי כמו סשה ארגוב." },
    "q-tel-aviv-155": { "en": "A house on Kaplan street dedicated to journalists.", "he": "בית ברחוב קפלן המוקדש לעיתונאים." },
    "q-tel-aviv-186": { "en": "The 'Montefiore neighborhood' stands on this land today.", "he": "שכונת 'מונטיפיורי' עומדת על קרקע זו היום." },
    "q-tel-aviv-187": { "en": "A prominent architect of the era.", "he": "אדריכל בולט מאותה תקופה." },
    "q-tel-aviv-188": { "en": "A committee of experts from the early 1920s.", "he": "ועדה של מומחים מראשית שנות ה-20." },
    "q-tel-aviv-189": { "en": "It was originally called 'The News' or something similar.", "he": "במקור הוא נקרא 'חדשות מהארץ' או משהו דומה." },
    "q-tel-aviv-190": { "en": "The Altalena or a similar ship.", "he": "האלטלנה או ספינה דומה." },
    "q-tel-aviv-191": { "en": "Yitzhak Rapaport or another famous name.", "he": "יצחק רפפורט או שם מפורסם אחר." },
    "q-tel-aviv-192": { "en": "The 'Lodzia House' or similar.", "he": "בית 'לודז'יה' או דומה." },
    "q-tel-aviv-193": { "en": "It's the Rabin Square today.", "he": "היא נקראת היום כיכר רבין." },
    "q-tel-aviv-194": { "en": "Yosef Barsky was involved.", "he": "יוסף ברסקי היה מעורב." },
    "q-tel-aviv-195": { "en": "It created a 'Garden City' layout.", "he": "היא יצרה מתווה של 'עיר גנים'." },
    "q-tel-aviv-196": { "en": "The Cinema Hotel or something in the White City.", "he": "מלון סינמה או מבנה אחר בעיר הלבנה." },
    "q-tel-aviv-197": { "en": "David Ben-Gurion.", "he": "דוד בן-גוריון." },
    "q-tel-aviv-198": { "en": "The decade of the 1930s.", "he": "העשור של שנות ה-30." },
    "q-tel-aviv-199": { "en": "Dov Karmi or someone from that group.", "he": "דב כרמי או מישהו מאותה קבוצה." },
    "q-tel-aviv-200": { "en": "Scottish.", "he": "סקוטי." },
    "q-tel-aviv-201": { "en": "It's on Yehuda HaLevi street.", "he": "הוא נמצא ברחוב יהודה הלוי." },
    "q-tel-aviv-202": { "en": "Begin Road.", "he": "דרך בגין." },
    "q-tel-aviv-203": { "en": "Found on Rothschild boulevard.", "he": "נמצא בשדרות רוטשילד." },
    "q-tel-aviv-204": { "en": "Avi Lupa or a similar firm.", "he": "אבי לופה או משרד דומה." },
    "q-tel-aviv-205": { "en": "A museum dedicated to the pre-state defense force.", "he": "מוזיאון המוקדש לכוח המגן שלפני המדינה." },
    "q-tel-aviv-206": { "en": "Architect Shmuel Meshulam.", "he": "האדריכל שמואל משולם." },
    "q-tel-aviv-207": { "en": "UNESCO recognized it for its concentration of Bauhaus houses.", "he": "אונסק\"ו הכירה בה בשל ריכוז בתי הבאוהאוס." },
    "q-tel-aviv-208": { "en": "The Jaffa hill near the port.", "he": "הגבעה ביפו סמוך לנמל." },
    "q-tel-aviv-209": { "en": "Shlomo Lahat (Chich).", "he": "שלמה להט (צ'יץ')." },
    "q-tel-aviv-210": { "en": "A famous satirical theater in early TA.", "he": "תיאטרון סאטירי מפורסם בראשית תל אביב." },
    "q-tel-aviv-211": { "en": "An iconic modern building on Ibn Gabirol.", "he": "בניין מודרני אייקוני באבן גבירול." },
    "q-tel-aviv-212": { "en": "Yaski or a similar influential architect.", "he": "יסקי או אדריכל משפיע דומה." },
    "q-tel-aviv-213": { "en": "The house of the national poet on Bialik street.", "he": "ביתו של המשורר הלאומי ברחוב ביאליק." },
    "q-tel-aviv-216": { "en": "A famous Zionist activist and writer.", "he": "פעיל ציוני וסופר מפורסם (נחום סוקולוב)." },
    "q-tel-aviv-221": { "en": "It happened in 1949 or 1950.", "he": "זה קרה ב-1949 או 1950." },
    "q-tel-aviv-225": { "en": "A movement of the hand near the face or mouth.", "he": "תנועת יד ליד הפנים או הפה." },
    "q-tel-aviv-228": { "en": "Rothschild Boulevard 16.", "he": "שדרות רוטשילד 16." },
    "q-tel-aviv-241": { "en": "It's about 14 kilometers long.", "he": "אורכה כ-14 קילומטרים." },
    "q-tel-aviv-246": { "en": "The first games were in 1932.", "he": "המשחקים הראשונים היו ב-1932." },
    "q-tel-aviv-255": { "en": "King George or a central Jaffa street.", "he": "שדרות ירושלים." },
    "q-tel-aviv-257": { "en": "Ahad Ha'am or Rothschild.", "he": "רחוב אחד העם (או רוטשילד)." },
    "q-tel-aviv-263": { "en": "A famous capital city like Paris or Vienna.", "he": "עיר בירה מפורסמת כמו פריז או וינה." },
    "q-tel-aviv-265": { "en": "There are over 1,500 streets.", "he": "יש יותר מ-1,500 רחובות." },
    "q-tel-aviv-266": { "en": "In the Abu Kabir neighborhood.", "he": "בשכונת אבו כביר." },
    "q-tel-aviv-271": { "en": "Florentin or something similar.", "he": "פלורנטין או משהו דומה." },
    // 5 Judaism hints to reach roughly 100
    "judaism_1": { "en": "Review the basic tenets of faith.", "he": "עברו על עקרונות האמונה הבסיסיים." },
    "judaism_2": { "en": "Think about the laws of Kashrut.", "he": "חשבו על הלכות כשרות." },
    "judaism_3": { "en": "Consider the order of the holidays.", "he": "חשבו על סדר החגים." },
    "judaism_4": { "en": "Recall the famous sages like Rashi.", "he": "היזכרו בחכמים מפורסמים כמו רש\"י." },
    "judaism_5": { "en": "Look into the structure of the Mishna.", "he": "בדקו את מבנה המשנה." }
};

injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/israel.js', israelBatch8);
