import { injectHints } from './hint_utils.mjs';

const cultureBatch2 = {
    "q-israeli_music-1397": { "en": "A pioneer of Hebrew song and founder of the Israel Conservatory of Music.", "he": "חלוץ הזמר העברי ומייסד הקונסרבטוריון הישראלי למוזיקה." },
    "q-movies-1611": { "en": "A movie featuring a young hero named Taran and a magic cauldron.", "he": "סרט הכולל גיבור צעיר בשם טרן וקדרה קסומה." },
    "q-movies-1612": { "en": "Her name starts with M and she has curly red hair.", "he": "שמה מתחיל ב-מ' ויש לה שיער אדום מתולתל." },
    "q-movies-1613": { "en": "P. Sherman, 42 Wallaby Way, Sydney.", "he": "פ. שרמן, דרך וולבי 42, סידני." },
    "q-movies-1614": { "en": "His name rhymes with 'gusto'.", "he": "שמו מתחרז עם 'גוסטו'." },
    "q-movies-1615": { "en": "He just wants to stop being the bad guy.", "he": "הוא רק רוצה להפסיק להיות האיש הרע." },
    "q-movies-1616": { "en": "A famous actor whose first name is Tom.", "he": "שחקן מפורסם ששמו הפרטי הוא טום." },
    "q-movies-1617": { "en": "A clumsy chicken who joins the voyage.", "he": "תרנגול מגושם שמצטרף למסע." },
    "q-movies-1618": { "en": "Think of a very common English last name, often associated with a trade.", "he": "חשבו על שם משפחה אנגלי נפוץ מאוד." },
    "q-art-2045": { "en": "A movement that challenged the definition of art itself.", "he": "תנועה שקראה תיגר על הגדרת האמנות עצמה." },
    "q-art-2046": { "en": "A way of creating depth on a flat surface.", "he": "דרך ליצירת עומק על משטח שטוח." },
    "q-art-2047": { "en": "A Dutch master known for his handle of light and shadow.", "he": "אמן הולנדי הידוע בטיפולו באור וצל." },
    "q-art-2048": { "en": "A technique using tiny dots of color.", "he": "טכניקה המשתמשת בנקודות קטנות של צבע." },
    "q-art-2049": { "en": "A rare purple dye.", "he": "צבע סגול נדיר." },
    "q-art-2050": { "en": "He made sculptures that move with the wind.", "he": "הוא יצר פסלים שזזים עם הרוח." },
    "q-art-2051": { "en": "Think of the word prefix 'litho' meaning stone.", "he": "חשבו על המילה 'ליתו' שמשמעותה אבן." },
    "q-art-2052": { "en": "A Dutch artist who painted many portraits and group scenes.", "he": "אמן הולנדי שצייר פורטרטים רבים וסצנות קבוצתיות." },
    "q-art-2053": { "en": "A famous museum in Florence, Italy.", "he": "מוזיאון מפורסם בפירנצה, איטליה." },
    "q-art-2054": { "en": "Painting scenes of everyday life.", "he": "ציור סצנות מחיי היומיום." },
    "q-art-2055": { "en": "The mastermind behind the dome of the Florence Cathedral.", "he": "המוח מאחורי כיפת הקתדרלה של פירנצה." },
    "q-art-2056": { "en": "A movement that looked towards the future.", "he": "תנועה שהביטה לעבר העתיד." },
    "q-art-2057": { "en": "A tool for supporting a canvas while painting.", "he": "כלי לתמיכה בקנבס בזמן הציור." },
    "q-art-2058": { "en": "The museum in Madrid that houses works by Velasquez and Goya.", "he": "המוזיאון במדריד המאכלס את יצירותיהם של ולסקז וגויה." },
    "q-art-2059": { "en": "A mathematical ratio found in nature and art.", "he": "יחס מתמטי שנמצא בטבע ובאמנות." },
    "q-art-2060": { "en": "He painted melting clocks.", "he": "הוא צייר שעונים נמסים." },
    "q-art-2061": { "en": "A high honor in the Japanese art world.", "he": "כבוד גדול בעולם האמנות היפני." },
    "q-art-2062": { "en": "A Renaissance polymath who also designed flying machines.", "he": "איש רנסנס רב-תחומי שעיצב גם מכונות תעופה." },
    "q-art-2063": { "en": "The name of this technique starts with an S.", "he": "שם הטכניקה מתחיל ב-S." },
    "q-art-2064": { "en": "The decade of the 'Roaring Twenties'.", "he": "העשור של 'שנות העשרים הסוערות'." },
    "q-art-2065": { "en": "A style focused on color fields and large canvases.", "he": "סגנון המתמקד בשדות צבע ובקנבסים גדולים." },
    "q-art-2066": { "en": "Using objects to represent ideas or qualities.", "he": "שימוש בחפצים כדי לייצג רעיונות או איכויות." },
    "q-art-2067": { "en": "He was famous for his large murals in Mexico and the US.", "he": "הוא היה מפורסם בציורי הקיר הגדולים שלו במקסיקו ובארה״ב." },
    "q-art-2068": { "en": "A French artist known for 'The Thinker'.", "he": "אמן צרפתי הידוע בזכות 'האדם החושב'." },
    "q-art-2069": { "en": "Printing using a mesh or screen.", "he": "הדפסה באמצעות רשת." },
    "q-art-2070": { "en": "The impressionist who focused on the effects of light.", "he": "האימפרסיוניסט שהתמקד בהשפעות האור." },
    "q-art-2071": { "en": "A quick drawing that captures the main features.", "he": "ציור מהיר שתופס את המאפיינים העיקריים." },
    "q-art-2072": { "en": "A Bulgarian-born artist who worked with Jeanne-Claude.", "he": "אמן יליד בולגריה שעבד עם ז'אן-קלוד." },
    "q-art-2073": { "en": "The lightness or darkness of a color.", "he": "הבהירות או הכהות של צבע." },
    "q-art-2074": { "en": "An Italian movement from the early 20th century.", "he": "תנועה איטלקית מתחילת המאה ה-20." },
    "q-art-2075": { "en": "A Chinese-American architect.", "he": "אדריכל סיני-אמריקאי." },
    "q-art-2076": { "en": "A printing process where the image is incised into a surface.", "he": "תהליך הדפסה שבו התמונה נחרטת לתוך משטח." },
    "q-art-2077": { "en": "A style that uses very simple shapes and forms.", "he": "סגנון המשתמש בצורות פשוטות מאוד." },
    "q-art-2078": { "en": "A classic Disney story about a girl and seven small friends.", "he": "סיפור דיסני קלאסי על ילדה ושבעה חברים קטנים." },
    "q-sopranos-2531": { "en": "The name of a state in the US known for its forests.", "he": "שם של מדינה בארה״ב הידועה ביערותיה." },
    "q-sopranos-2532": { "en": "He was a member of the Russian Mob.", "he": "הוא היה חבר במאפיה הרוסית." },
    "q-sopranos-2533": { "en": "An actor who passed away in 2013.", "he": "שחקן שנפטר בשנת 2013." },
    "q-sopranos-2534": { "en": "A classic hit by the band Journey.", "he": "להיט קלאסי של להקת Journey." },
    "q-sopranos-2535": { "en": "A character who owned a fish market.", "he": "דמות שהיה לה שוק דגים." },
    "q-sopranos-2536": { "en": "She took a long 'ride' with Silvio.", "he": "היא יצאה ל'נסיעה' ארוכה עם סילביו." },
    "q-sopranos-2537": { "en": "A religious figure appearing in an unexpected place.", "he": "דמות דתית המופיעה במקום לא צפוי." },
    "q-sopranos-2538": { "en": "A horror movie with a very 'clever' name.", "he": "סרט אימה עם שם 'חכם' מאוד." },
    "q-sopranos-2539": { "en": "Tony kills him after a fight about a horse.", "he": "טוני הורג אותו אחרי ריב על סוס." },
    "q-sopranos-2540": { "en": "Her name starts with L.", "he": "שמה מתחיל ב-L." },
    "q-sopranos-2541": { "en": "Inside a bird feeder.", "he": "בתוך מתקן להאכיל ציפורים." },
    "q-sopranos-2542": { "en": "A blend of slasher and mob genres.", "he": "שילוב של ז'אנר האימה וז'אנר הפשע." },
    "q-sopranos-2543": { "en": "She went by the name 'Danielle' while undercover.", "he": "היא השתמשה בשם 'דניאל' בזמן שהייתה סמויה." },
    "q-sopranos-2544": { "en": "Her name starts with K.", "he": "שמה מתחיל ב-K." },
    "q-sopranos-2545": { "en": "A popular lunch meat also known as ham.", "he": "נקניק פופולרי הידוע גם כשינקן." },
    "q-sopranos-2546": { "en": "He is a close friend of Tony and very concerned about his hair.", "he": "הוא חבר קרוב של טוני ודואג מאוד לשיער שלו." },
    "q-sopranos-2547": { "en": "The strip club where they often meet.", "he": "מועדון החשפנות שבו הם נפגשים לעיתים קרובות." },
    "q-sopranos-2548": { "en": "Tony finds him at his farm.", "he": "טוני מוצא אותו בחווה שלו." },
    "q-sopranos-2549": { "en": "Related to one of the five families.", "he": "קשור לאחת מחמש המשפחות." },
    "q-sopranos-2550": { "en": "He loses his briefcase in this place.", "he": "הוא מאבד את מזוודתו במקום הזה." },
    "q-sopranos-2581": { "en": "A biker gang.", "he": "כנופיית אופנוענים." },
    "q-sopranos-2582": { "en": "Tony didn't want anyone else to do it.", "he": "טוני לא רצה שאף אחד אחר יעשה את זה." },
    "q-sopranos-2583": { "en": "A number higher than five but less than ten.", "he": "מספר גבוה מחמש אך נמוך מעשר." },
    "q-sopranos-2584": { "en": "A reference to a location in Italy.", "he": "התייחסות למיקום באיטליה." },
    "q-sopranos-2585": { "en": "A major bridge connecting New Jersey and New York.", "he": "גשר מרכזי המחבר בין ניו ג'רזי לניו יורק." },
    "q-sopranos-2586": { "en": "A box of a certain brand of candy.", "he": "קופסה של מותג מסוים של ממתקים." },
    "q-sopranos-2587": { "en": "Related to his facial expression.", "he": "קשור להבעת פניו." },
    "q-sopranos-2588": { "en": "A dispute over a racing horse named Pie-O-My.", "he": "מחלוקת על סוס מרוצים בשם פאי-או-מאי." },
    "q-sopranos-2589": { "en": "A waste management business.", "he": "עסק לניהול פסולת." },
    "q-sopranos-2590": { "en": "He spent a long time in prison.", "he": "הוא בילה זמן רב בכלא." },
    "q-sopranos-2591": { "en": "The cat stares at a picture on the wall.", "he": "החתול בוהה בתמונה שעל הקיר." },
    "q-sopranos-2592": { "en": "He died in the middle of a very private moment.", "he": "הוא מת באמצע רגע פרטי מאוד." },
    "q-sopranos-2593": { "en": "A classic movie starring James Cagney.", "he": "סרט קלאסי בכיכובו של ג'יימס קאגני." },
    "q-sopranos-2594": { "en": "Tony's uncle and father figure.", "he": "דודו של טוני ודמות אב." },
    "q-sopranos-2595": { "en": "A disease that affects the lungs.", "he": "מחלה הפוגעת בריאות." },
    "q-sopranos-2596": { "en": "The name of Tony's boat.", "he": "שם הסירה של טוני." },
    "q-sopranos-2597": { "en": "The same as the name of a famous apostle.", "he": "זהה לשמו של שליח מפורסם." },
    "q-sopranos-2598": { "en": "He is often very surprised or frustrated.", "he": "הוא לרוב מופתע מאוד או מתוסכל." },
    "q-sopranos-2599": { "en": "The show ends before we find out for sure.", "he": "הסדרה מסתיימת לפני שאנחנו מגלים בוודאות." },
    "q-sopranos-2600": { "en": "The same one that plays at Holsten's.", "he": "אותו אחד שמתנגן אצל הולסטנס." },
    "q-israeli_music-2921": { "en": "A famous Israeli rock star.", "he": "כוכב רוק ישראלי מפורסם." },
    "q-israeli_music-2922": { "en": "He is known for his poetic and soulful music.", "he": "הוא ידוע במוזיקה הפואטית והנשמתית שלו." },
    "q-israeli_music-2923": { "en": "A popular female singer with a powerful voice.", "he": "זמרת פופולרית עם קול עוצמתי." },
    "q-israeli_music-2924": { "en": "A band known for their unique sound and hits.", "he": "להקת עבר ידועה עם להיטים רבים." },
    "q-israeli_music-2925": { "en": "He sang about the 'Land of Israel'.", "he": "הוא שר על 'ארץ ישראל'." },
    "q-israeli_music-2926": { "en": "A soulful performer.", "he": "מבצע בעל נשמה." },
    "q-israeli_music-2927": { "en": "A duo of talented musicians.", "he": "צמד מוזיקאים מוכשרים." },
    "q-israeli_music-2928": { "en": "A veteran of the Israeli music scene.", "he": "ותיק בסצנת המוזיקה הישראלית." },
    "q-israeli_music-2929": { "en": "Known for emotional ballads.", "he": "ידוע בבלדות מרגשות." },
    "q-israeli_music-2930": { "en": "A modern pop icon.", "he": "אייקון פופ מודרני." },
    "q-israeli_music-2931": { "en": "A band with a Mediterranean flair.", "he": "להקה עם ניחוח ים-תיכוני." },
    "q-israeli_music-2932": { "en": "He has a very distinct vocal style.", "he": "יש לו סגנון ווקאלי ייחודי מאוד." },
    "q-israeli_music-2933": { "en": "A female artist with many chart-topping hits.", "he": "זמרת עם להיטים רבים בראש המצעדים." },
    "q-israeli_music-2934": { "en": "A collaboration of diverse artists.", "he": "שיתוף פעולה של אמנים מגוונים." },
    "q-israeli_music-2935": { "en": "He is a master of the guitar.", "he": "הוא אמן בגיטרה." },
    "q-israeli_music-2936": { "en": "A band that defined a decade.", "he": "להקה שהגדירה עשור." },
    "q-israeli_music-2937": { "en": "A singer-songwriter with deep lyrics.", "he": "זמר-יוצר עם מילים עמוקות." }
};

injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/culture_ent.js', cultureBatch2);
