import { injectHints } from './hint_utils.mjs';

const batch13 = {
    // Food Science
    "q-food-1859": { "en": "Beaten egg whites trap air.", "he": "חלבוני ביצה מוקצפים לוכדים אוויר." },
    "q-food-1860": { "en": "Capsaicin.", "he": "קפסאיצין (Capsaicin)." },
    "q-food-1861": { "en": "Kibbeh.", "he": "קובה/קיבה (Kibbeh)." },
    "q-food-1862": { "en": "Extra virgin olive oil.", "he": "שמן זית כתית מעולה." },
    "q-food-1863": { "en": "Biscotti.", "he": "ביסקוטי (Biscotti)." },
    "q-food-1864": { "en": "The stalk.", "he": "הגבעול." },
    "q-food-1865": { "en": "Corn (Tamales, Arepas, etc.).", "he": "תירס (טמאלס, ארפאס וכו')." },
    "q-food-1866": { "en": "It's named after a British city.", "he": "השם שלו לקוח מעיר בריטית (Reuben Sandwich)." },
    "q-food-1867": { "en": "Penicillium mold.", "he": "עובש פניצילין (Penicillium)." },
    "q-food-1868": { "en": "Cardamom.", "he": "הל (Cardamom)." },
    "q-food-1869": { "en": "Bechamel sauce.", "he": "רוטב בשמל (Bechamel)." },
    "q-food-1870": { "en": "China.", "he": "סין." },
    "q-food-1871": { "en": "Coq au vin.", "he": "קוק או ון (Coq au Vin)." },
    "q-food-1872": { "en": "Fermentation.", "he": "תסיסה (Fermentation)." },
    "q-food-1873": { "en": "Baba Ghanoush.", "he": "בבא גאנוש." },
    "q-food-1874": { "en": "Vitamin K.", "he": "ויטמין K." },
    "q-food-1875": { "en": "Miso soup.", "he": "מרק מיסו." },
    "q-food-1876": { "en": "Mace.", "he": "מייס (Mace)." },
    "q-food-1877": { "en": "Focaccia.", "he": "פוקאצ'ה (Focaccia)." },
    "q-food-2279": { "en": "Binchotan charcoal.", "he": "פחם בינצ'וטן (Binchotan)." },
    "q-food-2280": { "en": "Spherification.", "he": "ספריפיקציה (Spherification)." },
    "q-food-2281": { "en": "Roquefort.", "he": "רוקפור (Roquefort)." },
    "q-food-2282": { "en": "Truffle.", "he": "כמהין (Truffle)." },
    "q-food-2283": { "en": "Durian (means 'thorn' in Malay).", "he": "דוריאן (פירושו 'קוץ' במלאית)." },
    "q-food-2284": { "en": "A bouquet garni (herbs tied together).", "he": "זר ירוק (Bouquet garni)." },
    "q-food-2285": { "en": "Tamarind or hibiscus.", "he": "תמרינד או כרכדה." },
    "q-food-2286": { "en": "Picung / Kepayang.", "he": "פיקונג/קפאיאנג." },
    "q-food-2287": { "en": "Ube (purple yam).", "he": "אובה (בטטה סגולה)." },
    "q-food-2288": { "en": "Conching.", "he": "קונצ'ינג (Conching)." },
    "q-food-2289": { "en": "Glutamate (umami taste).", "he": "גלוטמט (טעם אומאמי)." },
    "q-food-2290": { "en": "Narezushi.", "he": "נארזושי (Narezushi)." },
    "q-food-2291": { "en": "Bergamot orange.", "he": "ברגמוט (Bergamot)." },
    "q-food-2292": { "en": "Suet.", "he": "בשר חלב (Suet)." },
    "q-food-2293": { "en": "Mise en place (everything in its place).", "he": "מיז אן פלאס (הכל במקומו)." },
    "q-food-2294": { "en": "Asafoetida.", "he": "אסמודאוס / hing (אסאפוטידה)." },
    "q-food-2295": { "en": "Khachapuri.", "he": "חצ'פורי (Khachapuri)." },
    "q-food-2296": { "en": "Linalool or geraniol (rose/citrus).", "he": "לינלול או גרניול (ורדים/הדרים)." },
    "q-food-2297": { "en": "Brunoise cut (tiny cubes).", "he": "חיתוך ברונואז (קוביות זעירות)." },
    "q-food-2298": { "en": "Anchovies (for garum).", "he": "אנשובי (ל-גארום)." },
    "q-food-2324": { "en": "Auguste Escoffier.", "he": "אוגוסט אסקופייה (Escoffier)." },
    "q-food-2325": { "en": "Emilia-Romagna.", "he": "אמיליה-רומניה." },
    "q-food-2326": { "en": "Spherification.", "he": "ספריפיקציה." },
    "q-food-2327": { "en": "Beurre blanc.", "he": "בר בלאן (Beurre blanc)." },
    "q-food-2328": { "en": "The Maillard reaction.", "he": "תגובת מייאר." },
    "q-food-2329": { "en": "Dashi.", "he": "דאשי (Dashi)." },
    "q-food-2330": { "en": "Aspergillus oryzae (Koji mold).", "he": "פטרייה אספרגילוס אוריזה (קוג'י)." },
    "q-food-2331": { "en": "Amuse-bouche.", "he": "אמוז-בוש (Amuse-bouche)." },
    "q-food-2332": { "en": "Panko breadcrumbs.", "he": "פנקו (Panko)." },
    "q-food-2333": { "en": "A Salamander broiler.", "he": "סלמנדר גריל." },
    "q-food-2334": { "en": "Clarified butter (Ghee).", "he": "חמאה מזוקקת (גהי)." },
    "q-food-2335": { "en": "Veloute sauce.", "he": "רוטב ולוטה (Veloute)." },
    "q-food-2336": { "en": "Espagnole sauce.", "he": "רוטב אספניול (Espagnole)." },
    "q-food-2337": { "en": "Demi-glace.", "he": "דמי-גלאס (Demi-glace)." },
    "q-food-2338": { "en": "Chiffonade cut.", "he": "חיתוך שיפונד (Chiffonade)." },
    "q-food-2339": { "en": "Tempering chocolate.", "he": "טמפרור שוקולד (Tempering)." },
    "q-food-2340": { "en": "Bone marrow.", "he": "מוח עצם." },
    "q-food-2341": { "en": "Umami.", "he": "אומאמי (Umami)." },
    "q-food-2342": { "en": "Kobe beef.", "he": "בקר קובה (Kobe beef)." },
    "q-food-2343": { "en": "Souffle.", "he": "סופלה (Souffle)." },
    "q-food-2344": { "en": "A Terrine.", "he": "טרין (Terrine)." },
    "q-food-2345": { "en": "Zesting.", "he": "גרידה (Zesting)." },
    "q-food-2346": { "en": "Macerating.", "he": "מסרציה (Macerating)." },
    "q-food-2347": { "en": "Poaching.", "he": "בישול בנוזל (Poaching)." },
    "q-food-2348": { "en": "Panna cotta.", "he": "פאנה קוטה (Panna cotta)." },
    "q-food-2374": { "en": "A culinary preparation or cooking technique.", "he": "הכנה קולינרית או טכניקת בישול." },
    "q-food-2375": { "en": "A precise knife skill or cutting method.", "he": "מיומנות סכין מדויקת או שיטת חיתוך." },
    "q-food-2376": { "en": "A classical French sauce or preparation.", "he": "רוטב או הכנה צרפתית קלאסית." },
    "q-food-2377": { "en": "A molecular gastronomy process.", "he": "תהליך של גסטרונומיה מולקולרית." },
    "q-food-2378": { "en": "A French culinary term.", "he": "מונח קולינרי צרפתי." },
    "q-food-2379": { "en": "A specific ingredient used in cooking.", "he": "מרכיב ספציפי המשמש בבישול." },
    "q-food-2380": { "en": "Milk and roux (butter and flour).", "he": "חלב ורו (חמאה וקמח)." },
    "q-food-2381": { "en": "A French mother sauce.", "he": "רוטב אם צרפתי." },
    "q-food-2382": { "en": "To purify or clarify a stock.", "he": "לטהר או להבהיר ציר." },
    "q-food-2383": { "en": "A fine mesh strainer (Tamis or Chinois).", "he": "מסננת רשת דקה." },
    "q-food-2384": { "en": "A Japanese knife technique.", "he": "טכניקת סכין יפנית." },
    "q-food-2385": { "en": "A type of emulsion sauce.", "he": "סוג של רוטב אמולסיה." },
    "q-food-2386": { "en": "A culinary term for a dish preparation.", "he": "מונח קולינרי להכנת מנה." },
    "q-food-2387": { "en": "A preservation or fermentation process.", "he": "תהליך שימור או תסיסה." },
    "q-food-2388": { "en": "A professional kitchen tool or piece of equipment.", "he": "כלי מטבח מקצועי." },
    "q-food-2389": { "en": "Kombu seaweed and katsuobushi.", "he": "אצות קומבו ודג בוניטו מיובש." },
    "q-food-2390": { "en": "A specific cooking method.", "he": "שיטת בישול מסוימת." },
    "q-food-2391": { "en": "Gluten formation in dough.", "he": "יצירת גלוטן בבצק." },
    "q-food-2392": { "en": "A specific pasta shape or sauce.", "he": "צורת פסטה ספציפית או רוטב." },
    "q-food-2393": { "en": "En papillote (cooked in parchment).", "he": "בנייר (En papillote)." },
    "q-food-2394": { "en": "A deglaze liquid.", "he": "נוזל להמסת שאריות צלייה (deglaze)." },
    "q-food-2395": { "en": "A classic French knife cut.", "he": "חיתוך סכין צרפתי קלאסי." },
    "q-food-2396": { "en": "A cooking oil with a high smoke point.", "he": "שמן בישול בעל נקודת עשן גבוהה." },
    "q-food-2397": { "en": "The Sous Chef.", "he": "הסו-שף." },
    "q-food-2398": { "en": "A tubular pasta shape.", "he": "צורת פסטה צינורית." },
    "q-food-2399": { "en": "A ribbon-shaped pasta.", "he": "פסטה בצורת סרטים." },

    // World Landmarks
    "q-countries-3185": { "en": "Think of the Grand Canyon or Statue of Liberty.", "he": "חשבו על הגרנד קניון או פסל החירות." },
    "q-countries-3186": { "en": "Think of Mount Rushmore or Niagara Falls.", "he": "חשבו על הר ראשמור או מפלי ניאגרה." },
    "q-countries-3187": { "en": "Think of the Golden Gate Bridge or Yellowstone.", "he": "חשבו על גשר השער הזהב או ילוסטון." },
    "q-countries-3188": { "en": "Think of the White House or the Lincoln Memorial.", "he": "חשבו על הבית הלבן או אנדרטת לינקולן." },
    "q-countries-3189": { "en": "Think of the Las Vegas Strip or the Brooklyn Bridge.", "he": "חשבו על לאס וגאס או גשר ברוקלין." },
    "q-countries-3190": { "en": "Think of Yosemite or the Mississippi River.", "he": "חשבו על יוסמיטי או נהר המיסיסיפי." },
    "q-countries-3226": { "en": "Think of Big Ben or Buckingham Palace.", "he": "חשבו על ביג בן או ארמון בקינגהם." },
    "q-countries-3227": { "en": "Think of Stonehenge or the Tower of London.", "he": "חשבו על סטונהנג' או מגדל לונדון." },
    "q-countries-3228": { "en": "Think of the Palace of Westminster or the British Museum.", "he": "חשבו על ארמון וסטמינסטר או המוזיאון הבריטי." },
    "q-countries-3229": { "en": "Think of the White Cliffs of Dover or Hadrian's Wall.", "he": "חשבו על צוקי דובר הלבנים או חומת הדרייאנוס." },
    "q-countries-3230": { "en": "Think of Edinburgh Castle or Loch Ness.", "he": "חשבו על טירת אדינבורו או לוך נס." },
    "q-countries-3231": { "en": "Think of Windsor Castle or the Tate Modern.", "he": "חשבו על טירת וינדזור או מוזיאון טייט מודרן." },
    "q-countries-3232": { "en": "Think of the Shard or the National Gallery.", "he": "חשבו על שארד או הגלריה הלאומית." },
    "q-countries-3233": { "en": "Think of the Lake District or Sherwood Forest.", "he": "חשבו על מחוז האגמים או יער שרווד." },
    "q-countries-3234": { "en": "Think of Oxford or Cambridge University.", "he": "חשבו על אוניברסיטת אוקספורד או קיימברידג'." },
    "q-countries-3235": { "en": "Think of the SS Great Britain or Coventry Cathedral.", "he": "חשבו על הספינה SS Great Britain." },
    "q-countries-3236": { "en": "Think of Kew Gardens or Hampton Court Palace.", "he": "חשבו על גני קיו או ארמון המפטון קורט." },
    "q-countries-3237": { "en": "Think of the Roman Baths in Bath.", "he": "חשבו על המרחצאות הרומיים בבאת'." },
    "q-countries-3238": { "en": "Think of the Globe Theatre or St. Paul's Cathedral.", "he": "חשבו על תיאטרון הגלוב או קתדרלת סנט פול." },
    "q-countries-3239": { "en": "Think of Blenheim Palace or Chatsworth House.", "he": "חשבו על ארמון בלנהיים." },
    "q-countries-3240": { "en": "Think of the Angel of the North or the Falkirk Wheel.", "he": "חשבו על מלאך הצפון (Angel of the North)." }
};

injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/sports_life.js', batch13);
injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/world.js', batch13);
