import { injectHints } from './hint_utils.mjs';

const sportsBatch9 = {
    "q-patisserie-1244": { "en": "Gradually add hot milk to prevent the eggs from scrambling.", "he": "הוסיפו חלב חם בהדרגה כדי למנוע מהביצים להיקרש." },
    "q-patisserie-1246": { "en": "The correct temp to ensure the dough cooks without burning.", "he": "הטמפרטורה הנכונה להבטחת בישול הבצק ללא חריכה." },
    "q-patisserie-1248": { "en": "It protects the fruit and makes the tart look professional.", "he": "זה מגן על הפירות ומעניק לטארט מראה מקצועי." },
    "q-patisserie-1250": { "en": "Aligns the crystals for a hard, shiny finish.", "he": "מסדר את הגבישים לקבלת גימור קשה ומבריק." },
    "q-patisserie-1251": { "en": "The butter will melt prematurely, destroying the flaky layers.", "he": "החמאה תימס בטרם עת ותהרוס את השכבות הפריכות." },
    "q-patisserie-1254": { "en": "They won't form a skin and will crack during baking.", "he": "הם לא יפתחו קרום וייסדקו בזמן האפייה." },
    "q-patisserie-1255": { "en": "Removes moisture so the dough can absorb eggs and puff up.", "he": "מסיר לחות כדי שהבצק יוכל לספוג ביצים ולהתנפח." },
    "q-patisserie-1256": { "en": "Fat prevents the egg whites from developing a strong foam.", "he": "שומן מונע מחלבוני הביצה לפתח קצף חזק." },
    "q-patisserie-1261": { "en": "They will stay dense and absorb too much fat.", "he": "הן יישארו דחוסות ויספגו יותר מדי שומן." },
    "q-patisserie-1262": { "en": "Ensures the fat is integrated without breaking the gluten.", "he": "מבטיח שהשומן ישולב מבלי לשבור את הגלוטן." },
    "q-patisserie-1263": { "en": "To create a beautiful sheen and seal in moisture.", "he": "כדי ליצור ברק יפה ולאטום את הלחות." },
    "q-patisserie-1264": { "en": "The mousse will stay liquid and won't hold its shape.", "he": "המוס יישאר נוזלי ולא ישמור על צורתו." },
    "q-patisserie-1269": { "en": "A moist surface causes the macarons to explode in heat.", "he": "משטח לח גורם למקרונים להתפוצץ בחום." },
    "q-patisserie-1271": { "en": "Egg whites are highly sensitive to any trace of oil.", "he": "חלבונים רגישים מאוד לכל זכר של שמן." },
    "q-patisserie-1273": { "en": "The chocolate and cream will separate into a grainy mess.", "he": "השוקולד והשמנת ייפרדו למסה גרגירית." },
    "q-patisserie-1275": { "en": "Glucose provides a barrier against crystals forming.", "he": "הגלוקוז מהווה מחסום נגד היווצרות גבישים." },
    "q-patisserie-1276": { "en": "Instant heat creates the steam necessary for rising.", "he": "חום מיידי יוצר את האדים הדרושים לתפיחה." },
    "q-patisserie-1277": { "en": "The butter will bleed out, making the bread greasy.", "he": "החמאה תזלוג החוצה ותהפוך את הלחם לשומני." },
    "q-patisserie-1278": { "en": "Adds a protective, glossy layer to fresh fruit.", "he": "מוסיף שכבת הגנה מבריקה לפירות טריים." },
    "q-patisserie-1279": { "en": "Structural integrity for airy, whipped desserts.", "he": "שלמות מבנית לקינוחים אווריריים ומוקצפים." },
    "q-patisserie-1281": { "en": "Puff pastry depends on solid fat to create lift.", "he": "בצק עלים תלוי בשומן מוצק כדי ליצור הרמה." },
    "q-patisserie-1282": { "en": "You'll deflate the eggs and the cake won't rise.", "he": "תוציאו את האוויר מהביצים והעוגה לא תתפח." },
    "q-patisserie-1283": { "en": "The bread will be brittle and flat without gluten.", "he": "הלחם יהיה פריך ושטוח ללא גלוטן." },
    "q-patisserie-1285": { "en": "Crucial for the hollow center of a profiterole.", "he": "קריטי למרכז החלול של הפחזנית." },
    "q-patisserie-1286": { "en": "Maximum volume requires a perfectly clean environment.", "he": "נפח מקסימלי דורש סביבה נקייה לחלוטין." },
    "q-patisserie-1288": { "en": "Emulsification creates the smooth, luxurious texture.", "he": "האמולסיה יוצרת את המרקם החלק והיוקרתי." },
    "q-patisserie-1289": { "en": "Slowly heating prevents the egg protein from curdling.", "he": "חימום איטי מונע מחלבון הביצה להיקרש." },
    "q-patisserie-1291": { "en": "Prevents soggy dough and allows for perfect coloring.", "he": "מונע בצק ספוג בשמן ומאפשר השחמה מושלמת." },
    "q-patisserie-1292": { "en": "Butter must be added in stages for rich brioche.", "he": "יש להוסיף חמאה בשלבים עבור בריוש עשיר." },
    "q-patisserie-1293": { "en": "Fruit appearance will degrade very quickly.", "he": "מראה הפרי יתדרדר מהר מאוד." },
    "q-patisserie-1294": { "en": "Without gelatin, it's just a thick cream, not a mousse.", "he": "ללא ג'לטין, זה פשוט קרם סמיך, לא מוס." },
    "q-patisserie-1296": { "en": "To prevent the butter from leaking during the process.", "he": "כדי למנוע מהחמאה לדלוף במהלך התהליך." },
    "q-patisserie-1298": { "en": "Kneading creates the 'stretch' needed to hold air.", "he": "הלישה יוצרת את ה'מתיחה' הדרושה להחזקת אוויר." },
    "q-patisserie-1300": { "en": "Essential for 'puffing' the dough with steam later.", "he": "חיוני ל'ניפוח' הבצק בעזרת אדים מאוחר יותר." },
    "q-patisserie-1305": { "en": "Stabilizes the sugar molecules to prevent graininess.", "he": "מייצב את מולקולות הסוכר למניעת גרגיריות." },
    "q-patisserie-1306": { "en": "They will stay raw inside and brown too fast outside.", "he": "הן יישארו נאוות בפנים וישחימו מהר מדי בחוץ." },
    "q-patisserie-1308": { "en": "High-shine finish is the hallmark of quality pastry.", "he": "גימור מבריק הוא סימן היכר של קונדיטוריה איכותית." },
    "q-patisserie-1310": { "en": "Chocolate won't set firmly and will melt at a touch.", "he": "השוקולד לא יתקשה ויימס במגע." },
    "q-patisserie-1311": { "en": "Each fold needs to stay cold to remain distinct.", "he": "כל קיפול צריך להישאר קר כדי להישאר נפרד." },
    "q-patisserie-1315": { "en": "Moisture is the enemy of a light, risen choux.", "he": "הלחות היא האויב של בצק רבוך קליל ותפוח." },
    "q-patisserie-1316": { "en": "Oil disrupts the bond between egg protein and air.", "he": "שמן משבש את החיבור בין חלבון הביצה לאוויר." },
    "q-patisserie-1317": { "en": "Cold water keeps the butter pieces solid.", "he": "מים קרים שומרים על חתיכות החמאה מוצקות." },
    "q-patisserie-1320": { "en": "A proven method to stop large crystals from growing.", "he": "שיטה מוכחת לעצירת גדילת גבישים גדולים." },
    "q-patisserie-1321": { "en": "Ensures the crust is robust while the inside is soft.", "he": "מבטיח שהקרום יהיה חזק בזמן שהפנים רך." },
    "q-patisserie-1328": { "en": "Without kneading, your bread won't have a structure.", "he": "ללא לישה, ללחם שלכם לא יהיה מבנה." },
    "q-patisserie-1331": { "en": "Meringue needs total cleanliness for stability.", "he": "מרנג זקוק לניקיון מוחלט ליציבות." },
    "q-patisserie-1333": { "en": "Combines fat and water into a smooth, shiny state.", "he": "משלב שומן ומים למצב חלק ומבריק." },
    "q-patisserie-1334": { "en": "Slow addition protects the yolks from overcooking.", "he": "הוספה איטית מגנה על החלמונים מבישול יתר." },
    "q-patisserie-1335": { "en": "Essential for clear, professional-grade syrups.", "he": "חיוני לסירופים צלולים ברמה מקצועית." },
    "q-patisserie-1337": { "en": "Prevents the fat from over-lubricating the dough.", "he": "מונע מהשומן לשמן את הבצק יותר מדי." },
    "q-patisserie-1338": { "en": "It seals the fruit to prevent browning.", "he": "זה אוטם את הפרי כדי למנוע השחמה." },
    "q-patisserie-1342": { "en": "Fold as if the bubbles were fragile crystals.", "he": "קפלו כאילו בועות האוויר היו גבישים שבירים." },
    "q-patisserie-1344": { "en": "No rest equals no feet on your macarons.", "he": "אין מנוחה פירושו שאין 'רגליים' למקרונים." },
    "q-patisserie-1346": { "en": "Grease kills the volume of the egg foam.", "he": "שומן הורס את הנפח של קצף הביצים." },
    "q-patisserie-1349": { "en": "Temper to avoid 'scrambled' dessert outcomes.", "he": "השוו טמפרטורות כדי להימנע מקינוח בטעם חביתה." },
    "q-patisserie-1351": { "en": "The doughnuts will be oily and unappetizing.", "he": "הסופגניות יהיו שומניות ולא מעוררות תיאבון." },
    "q-patisserie-1355": { "en": "Tempering gives chocolate its snap and gloss.", "he": "טמפרור נותן לשוקולד את הברק והשבירה (Snap)." },
    "q-patisserie-1360": { "en": "Removing water is the magic behind choux pastry.", "he": "הסרת המים היא הקסם שמאחורי בצק רבוך." },
    "q-patisserie-1362": { "en": "Warm butter results in a tough, hard pie crust.", "he": "חמאה חמה מביאה לקרום פאי קשה." },
    "q-patisserie-1363": { "en": "Ganache relies on a perfect fat-to-liquid bond.", "he": "גנאש מסתמך על חיבור מושלם בין שומן לנוזל." },
    "q-food-1785": { "en": "Think of raw fish and rice.", "he": "חשבו על דג נא ואורז." },
    "q-food-1786": { "en": "Associated with peppers and heat.", "he": "מזוהה עם פלפלים וחריפות." },
    "q-food-1787": { "en": "A black or white 'diamond' found in woods.", "he": "יהלום שחור או לבן שנמצא ביערות (כמהין)." },
    "q-food-1788": { "en": "Compare with red or yellow varieties.", "he": "השוו לזנים אדומים או צהובים." },
    "q-food-1789": { "en": "Found in the skins of dark grapes.", "he": "נמצא בקליפות של ענבים כהים (רזברטרול)." },
    "q-food-1790": { "en": "A common supplement for vegans.", "he": "תוסף תזונה נפוץ לטבעונים (B12)." },
    "q-food-1791": { "en": "Associated with high-end Wagyu beef.", "he": "מזוהה עם בקר וואגיו יוקרתי." },
    "q-food-1792": { "en": "It's brown, sweet, and often comes in sticks.", "he": "הוא חום, מתוק ולעתים מגיע במקלות (קינמון)." },
    "q-food-1793": { "en": "It starts with 'W' and is often a protein supplement.", "he": "זה מתחיל ב-'W' (מי גבינה - Whey)." },
    "q-food-1794": { "en": "Very thin layers, name sounds like 'Phyllis'.", "he": "שכבות דקות מאוד, השם נשמע כמו פילו." },
    "q-food-1795": { "en": "Is it a fruit, vegetable, or something else?", "he": "האם זה פרי, ירק או משהו אחר?" },
    "q-food-1796": { "en": "Think of a traditional French onion or bean soup.", "he": "חשבו על מרק בצל או שעועית צרפתי." },
    "q-food-1797": { "en": "A small country famous for watches and banking.", "he": "מדינה קטנה המפורסמת בשעונים ובבנקאות (שוויץ)." },
    "q-food-1798": { "en": "Ends with '-ose'.", "he": "מסתיים ב-'-וז' (סוכרוז)." },
    "q-food-1799": { "en": "You only eat the stalk, never the leaves.", "he": "אוכלים רק את הגבעול, לעולם לא את העלים." },
    "q-food-1800": { "en": "Kopi Luwak is the famous name.", "he": "קופי לואק הוא השם המפורסם." },
    "q-food-1801": { "en": "Commonly used in professional kitchens for prep.", "he": "בשימוש נפוץ במטבחים מקצועיים להכנות (מיז אן פלאס)." },
    "q-food-1802": { "en": "Bromelain is found in this tropical fruit.", "he": "ברומליין נמצא בפרי הטרופי הזה (אננס)." },
    "q-food-1803": { "en": "It's a type of sausage made with... crimson liquid.", "he": "זה סוג של נקניקייה העשויה מנוזל אדום עמוק (דם)." },
    "q-food-1804": { "en": "Maybe it's a spice or a method.", "he": "אולי זה תבלין או שיטת הכנה." },
    "q-food-1805": { "en": "The name means 'under vacuum' in French.", "he": "השם פירושו 'תחת ואקום' בצרפתית (סו-ויד)." },
    "q-food-1806": { "en": "A crocus flower native to SW Asia.", "he": "פרח כרכוס שמקורו בדרום-מערב אסיה." },
    "q-food-1807": { "en": "Commonly used in ice cream or jams.", "he": "בשימוש נפוץ בגלידות או ריבות (אגר אגר וכדומה)." },
    "q-food-1808": { "en": "Developed shortly after WWII.", "he": "פותח זמן קצר לאחר מלחמת העולם השנייה (שנות ה-40)." },
    "q-food-1809": { "en": "Helps with calcium absorption.", "he": "עוזר בספיגת סידן (ויטמין D)." },
    "q-food-1810": { "en": "It's spicy, fermented cabbage.", "he": "זה כרוב חריף ומתסס (קימצ'י)." },
    "q-food-1811": { "en": "The same gas we breathe out.", "he": "אותו גז שאנחנו נשיפה החוצה (פחמן דו-חמצני)." },
    "q-food-1812": { "en": "It's like a pancake but much thinner.", "he": "זה כמו פנקייק אבל הרבה יותר דק (קרפ)." },
    "q-food-1813": { "en": "Found in many Middle Eastern desserts.", "he": "נמצא בקינוחים מזרח-תיכוניים רבים (פיסטוק)." },
    "q-food-1814": { "en": "Starts with 'P' (Potato).", "he": "מתחיל ב-'P' (תפוח אדמה)." },
    "q-food-1815": { "en": "Often used as a sugar substitute.", "he": "משמש לעתים קרובות כתחליף סוכר (סטיביה)." },
    "q-food-1816": { "en": "Maybe it's a star or dragon fruit.", "he": "אולי זה פרי כוכב או פרי הדרקון." },
    "q-food-1817": { "en": "A very popular bean flavor used in baking.", "he": "טעם פופולרי מאוד של פולים לשימוש באפייה (וניל)." },
    "q-food-1818": { "en": "It's the stuff in flour that makes dough stretchy.", "he": "זה החומר בקמח שהופך את הבצק למתוח (גלוטן)." },
    "q-food-1819": { "en": "Think of a country between Europe and Asia.", "he": "חשבו על מדינה בין אירופה לאסיה (טורקיה)." },
    "q-food-1820": { "en": "The name sounds like 'Caramel'.", "he": "השם נשמע כמו 'קרמל' (קרמליזציה)." },
    "q-food-1821": { "en": "C is for...?", "he": "ויטמין שמתחיל באות ג'?" },
    "q-food-1822": { "en": "Associated with bananas.", "he": "מזוהה עם בננות." },
    "q-food-1823": { "en": "A green, fatty fruit used for toast.", "he": "פרי ירוק ושומני המשמש לממרח על טוסט (אבוקדו)." },
    "q-food-1824": { "en": "It's called Hollandaise.", "he": "הוא נקרא הולנדז." }
};

injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/sports_life.js', sportsBatch9);
