import { injectHints } from './hint_utils.mjs';

const sportsBatch7 = {
    "q-patisserie-1021": { "en": "The dough will absorb too much oil at lower temperatures.", "he": "הבצק יספוג יותר מדי שמן בטמפרטורות נמוכות יותר." },
    "q-patisserie-1022": { "en": "To develop the gluten structure before adding the weight of the fat.", "he": "כדי לפתח את מבנה הגלוטן לפני הוספת כובד השומן." },
    "q-patisserie-1025": { "en": "The chocolate will be soft, dull, and won't 'snap'.", "he": "השוקולד יהיה רך, עמום ולא 'יישבר' בצורה חדה." },
    "q-patisserie-1026": { "en": "To keep the butter layers solid and distinct for flaky results.", "he": "כדי לשמור על שכבות החמאה מוצקות ונפרדות לתוצאה פריכה." },
    "q-patisserie-1027": { "en": "To maintain the airy volume created by the beaten eggs.", "he": "כדי לשמור על הנפח האווירי שנוצר מהקצפת הביצים." },
    "q-patisserie-1030": { "en": "To evaporate moisture so the pastry can expand and hold its shape in the oven.", "he": "לאידוי הלחות כדי שהבצק יוכל להתרחב ולשמור על צורתו בתנור." },
    "q-patisserie-1035": { "en": "To prevent sugar crystallization during the boiling process.", "he": "כדי למנוע התגבשות סוכר בזמן תהליך ההרתחה." },
    "q-patisserie-1036": { "en": "The ideal temperature for a golden crust and cooked interior.", "he": "הטמפרטורה האידיאלית לקבלת קרום זהוב ופנים מבושל." },
    "q-patisserie-1039": { "en": "To give the airy mousse a stable, sliceable structure.", "he": "כדי לתת למוס האווירי מבנה יציב שניתן לפרוס." },
    "q-patisserie-1040": { "en": "To align the cocoa butter crystals for a shiny and firm finish.", "he": "כדי לסדר את גבישי חמאת הקקאו למרקם מבריק ומוצק." },
    "q-patisserie-1041": { "en": "The butter will melt into the dough, ruining the flaky layers.", "he": "החמאה תימס לתוך הבצק ותהרוס את השכבות הדקיקות." },
    "q-patisserie-1043": { "en": "To develop the gluten strands that give the bread its elasticity.", "he": "כדי לפתח את סיבי הגלוטן הנותנים ללחם את האלסטיות שלו." },
    "q-patisserie-1047": { "en": "The fat will melt, and the crust will become tough instead of flaky.", "he": "השומן יימס והבצק יהיה קשה במקום פריך." },
    "q-patisserie-1049": { "en": "The eggs will scramble from the sudden high heat.", "he": "הביצים ייקרשו (יהפכו לחביתה) מהחום הגבוה הפתאומי." },
    "q-patisserie-1050": { "en": "To interfere with the formation of large sugar crystals.", "he": "כדי להפריע להיווצרות גבישי סוכר גדולים." },
    "q-patisserie-1051": { "en": "It ensures the outside is crisp while the inside stays light.", "he": "זה מבטיח שהחוץ יהיה פריך בזמן שהפנים נשאר קליל." },
    "q-patisserie-1053": { "en": "To provide a brilliant shine and prevent the fruit from drying out.", "he": "כדי לספק ברק מרהיב ולמנוע מהפירות להתייבש." },
    "q-patisserie-1054": { "en": "It ensures the mousse maintains its shape at room temperature.", "he": "זה מבטיח שהמוס ישמור על צורתו בטמפרטורת החדר." },
    "q-patisserie-1055": { "en": "For a professional finish with a high sheen and a clean break.", "he": "לגימור מקצועי עם ברק גבוה ושבירה נקייה." },
    "q-patisserie-1056": { "en": "This creates 'lift' as the moisture in the cold butter turns to steam.", "he": "זה יוצר 'הרמה' כשהלחות בחמאה הקרה הופכת לאדים." },
    "q-patisserie-1057": { "en": "If you stir too hard, you'll lose the air that makes the cake rise.", "he": "אם תערבבו חזק מדי, תאבדו את האוויר שגורם לעוגה לתפוח." },
    "q-patisserie-1061": { "en": "Even a tiny amount of fat will prevent the egg whites from foaming.", "he": "אפילו כמות קטנה של שומן תמנע מחלבוני הביצה להקציף." },
    "q-patisserie-1062": { "en": "To keep the bits of fat solid until they hit the hot oven.", "he": "כדי לשמור על חתיכות השומן מוצקות עד שהן מגיעות לתנור החם." },
    "q-patisserie-1065": { "en": "Glucose acts as a stabilizing agent against crystallization.", "he": "גלוקוז משמש כגורם מייצב נגד התגבשות." },
    "q-patisserie-1068": { "en": "The glaze creates a seal that protects the fruit's appearance.", "he": "הזיגוג יוצר אטימה המגינה על מראה הפרי." },
    "q-patisserie-1070": { "en": "Without it, the chocolate will lose its shape and bloom.", "he": "בלי זה, השוקולד יאבד את צורתו ויפתח כתמים לבנים." },
    "q-patisserie-1072": { "en": "To preserve the delicate structure of the beaten eggs.", "he": "כדי לשמר את המבנה העדין של הביצים המוקצפות." },
    "q-patisserie-1077": { "en": "The cold water keeps the fat from melting prematurely.", "he": "המים הקרים מונעים מהשומן להמיס בטרם עת." },
    "q-patisserie-1080": { "en": "To create a smooth, clear syrup without crystals.", "he": "כדי ליצור סירופ חלק וצלול ללא גבישים." },
    "q-patisserie-1081": { "en": "The high heat creates a rapid rise and a thin crust.", "he": "החום הגבוה יוצר תפיחה מהירה וקרום דק." },
    "q-patisserie-1082": { "en": "Adding fat slowly prevents it from breaking the gluten network.", "he": "הוספת שומן באטיות מונעת ממנו לשבור את רשת הגלוטן." },
    "q-patisserie-1083": { "en": "The fruit will look dull and may turn brown quickly.", "he": "הפירות ייראו עמומים ועלולים להשחים במהירות." },
    "q-patisserie-1088": { "en": "Kneading aligns the proteins into a strong, stretchy web.", "he": "הלישה מסדרת את החלבונים לרשת חזקה וגמישה." },
    "q-patisserie-1092": { "en": "It's essential for achieving a flaky, 'short' texture.", "he": "זה חיוני להשגת מרקם פריך ומתפורר." },
    "q-patisserie-1094": { "en": "To gradually raise the temperature of the egg yolks.", "he": "כדי להעלות בהדרגה את טמפרטורת החלמונים." },
    "q-patisserie-1095": { "en": "The syrup will likely turn into a hard, grainy mass of sugar.", "he": "הסירופ ככל הנראה יהפוך למסה קשה וגרעינית של סוכר." },
    "q-patisserie-1096": { "en": "They will stay greasy and heavy instead of light and airy.", "he": "הן יישארו שומניות וכבדות במקום להיות קלילות ואווריריות." },
    "q-patisserie-1097": { "en": "The butter will leak out, and the bread will be oily and dense.", "he": "החמאה תדלוף החוצה, והלחם יהיה שומני ודחוס." },
    "q-patisserie-1098": { "en": "The tart will lose its professional shine and fresh look.", "he": "הטארט יאבד את הברק המקצועי והמראה הטרי שלו." },
    "q-patisserie-1100": { "en": "Allows it to be molded easily while maintaining a beautiful shine.", "he": "מאפשר לעצב אותו בקלות תוך שמירה על ברק יפה." },
    "q-patisserie-1103": { "en": "To ensure the bread can trap gas and rise properly.", "he": "כדי להבטיח שהלחם יוכל לכלוא גזים ולתפוח כראוי." },
    "q-patisserie-1104": { "en": "Allows a 'skin' to form, which creates the famous macaron 'feet'.", "he": "מאפשר היווצרות 'עור', שיוצר את ה'רגליים' המפורסמות של המקרון." },
    "q-patisserie-1107": { "en": "To prevent the fat from coating the flour too thoroughly early on.", "he": "כדי למנוע מהשומן לצפות את הקמח בצורה יסודית מדי בשלב מוקדם." },
    "q-patisserie-1108": { "en": "To create a stable bond between the fat in chocolate and the liquid cream.", "he": "כדי ליצור חיבור יציב בין השומן שבשוקולד לבין השמנת הנוזלית." },
    "q-patisserie-1116": { "en": "The pastry won't puff up, and it will be dense instead of layered.", "he": "הבצק לא יתנפח ויהיה דחוס במקום להיות מורכב משכבות." },
    "q-patisserie-1117": { "en": "Protecting the air bubbles is the key to a light sponge.", "he": "הגנה על בועות האוויר היא המפתח לעוגת ספוג קלה." },
    "q-patisserie-1120": { "en": "Evaporating water is what allows the steam to puff the pastry later.", "he": "אידוי המים הוא מה שמאפשר לאדים לנפח את הבצק מאוחר יותר." },
    "q-patisserie-1121": { "en": "The proteins cannot form a stable network around fat molecules.", "he": "החלבונים אינם יכולים ליצור רשת יציבה סביב מולקולות שומן." },
    "q-patisserie-1122": { "en": "Warm water melts the butter, leading to a tough, greasy crust.", "he": "מים חמים ממיסים את החמאה, מה שמוביל לקרום קשה ושומני." },
    "q-patisserie-1125": { "en": "You risk the entire batch crystallizing into a solid block.", "he": "אתם מסתכנים בכך שכל הכמות תתגבש לבלוק מוצק." },
    "q-patisserie-1128": { "en": "The tart will go from 'professional' to 'home-made' in appearance.", "he": "הטארט יעבור ממראה 'מקצועי' למראה 'ביתי' בגלל חוסר הברק." },
    "q-patisserie-1129": { "en": "Provides the structural integrity needed for a mousse to hold its shape.", "he": "מספק את השלמות המבנית הדרושה למוס כדי לשמור על צורתו." },
    "q-patisserie-1131": { "en": "Vital for maintaining the distinct 'thousand layers' of the pastry.", "he": "חיוני לשמירה על אלף השכבות הנפרדות של הבצק." },
    "q-patisserie-1135": { "en": "The double-cooking process (pan then oven) is unique to this dough.", "he": "תהליך הבישול הכפול (בסיר ואז בתנור) ייחודי לבצק זה." },
    "q-patisserie-1136": { "en": "Fat is the natural enemy of a stable egg white foam.", "he": "שומן הוא האויב הטבעי של קצף חלבונים יציב." },
    "q-patisserie-1138": { "en": "The ganache will 'split', showing oily droplets on the surface.", "he": "הגנאש 'יישבר' ויופיעו טיפות שומניות על פני השטח." },
    "q-patisserie-1142": { "en": "The dough will be heavy and won't develop those beautiful air pockets.", "he": "הבצק יהיה כבד ולא יפתח את כיסי האוויר היפים." },
    "q-patisserie-1144": { "en": "Gelatin creates a mesh that traps the air and liquid in place.", "he": "הג'לטין יוצר רשת הלוכדת את האוויר והנוזל במקומם." },
    "q-patisserie-1145": { "en": "The finish will be greyish and the chocolate won't click when broken.", "he": "הגימור יהיה אפרפר והשוקולד לא 'יקליק' כשתשברו אותו." },
    "q-patisserie-1149": { "en": "They will crack or fail to rise properly without a foot.", "he": "הם ייסדקו או ייכשלו בתפיחה נכונה ללא ה'רגליים'." },
    "q-patisserie-1150": { "en": "The dough needs to be dry enough to absorb eggs later.", "he": "הבצק צריך להיות יבש מספיק כדי לספוג את הביצים מאוחר יותר." },
    "q-patisserie-1152": { "en": "Heat equals melted fat, which equals a failed pie crust.", "he": "חום שווה לשומן מומס, מה שמוביל לבצק פאי שנכשל." },
    "q-patisserie-1154": { "en": "A critical step in almost every professional custard-based dessert.", "he": "שלב קריטי בכמעט כל קינוח מקצועי המבוסס על קרם." },
    "q-patisserie-1159": { "en": "Enables the mousse to be light and airy yet solid enough to slice.", "he": "מאפשר למוס להיות קל ואוורירי אך מוצק מספיק לפריסה." },
    "q-patisserie-1164": { "en": "Resting helps the surface dry and stabilizes the internal structure.", "he": "המנוחה עוזרת לפני השטח להתייבש ומייצבת את המבנה הפנימי." },
    "q-patisserie-1169": { "en": "Prevents the eggs from 'shocking' and cooking on contact with hot milk.", "he": "מונע מהביצים לקבל 'שוק' ולהתבשל במגע עם חלב חם." },
    "q-patisserie-1170": { "en": "You'll end up with a pan of sugar crystals instead of smooth syrup.", "he": "תסיימו עם סיר מלא בגבישי סוכר במקום סירופ חלק." },
    "q-patisserie-1173": { "en": "It creates an edible 'varnish' that protects and beautifies.", "he": "זה יוצר 'לכה' אכילה המגינה ומיפה." },
    "q-patisserie-1174": { "en": "Without it, the mousse would just be a rich, runny cream.", "he": "בלי זה, המוס יהיה פשוט קרם עשיר ונוזלי." },
    "q-patisserie-1176": { "en": "If the layers merge, the pastry will be greasy and flat.", "he": "אם השכבות יתמזגו, הבצק יהיה שומני ושטוח." },
    "q-patisserie-1177": { "en": "Treat the air bubbles like delicate glass; don't break them.", "he": "התייחסו לבועות האוויר כאל זכוכית עדינה; אל תשברו אותן." },
    "q-patisserie-1178": { "en": "Kneading is the only way to build the 'skeleton' of the bread.", "he": "לישה היא הדרך היחידה לבנות את ה'שלד' של הלחם." },
    "q-patisserie-1179": { "en": "Essential for the high internal pressure that creates the 'feet'.", "he": "חיוני ללחץ הפנימי הגבוה שיוצר את ה'רגליים'." },
    "q-patisserie-1180": { "en": "A moist dough won't have the strength to puff up in the oven.", "he": "בצק לח לא יהיה חזק מספיק כדי להתנפח בתנור." },
    "q-patisserie-1184": { "en": "Ensures the final cream is silky smooth without any bits of cooked egg.", "he": "מבטיח שהקרם הסופי יהיה חלק כמשי ללא חתיכות ביצה מבושלת." },
    "q-patisserie-1185": { "en": "Glucose provides a crystal-free journey to the desired sugar stage.", "he": "גלוקוז מבטיח תהליך ללא גבישים עד להגעה לשלב הסוכר הרצוי." },
    "q-patisserie-1186": { "en": "Ensures the dough cooks through before the outside gets too dark.", "he": "מבטיח שהבצק יתבשל מבפנים לפני שהחוץ נהיה כהה מדי." },
    "q-patisserie-1189": { "en": "Gelatin turns a flavored liquid into a stable, airy dream.", "he": "הג'לטין הופך נוזל בטעמים לחלום יציב ואוורירי." },
    "q-patisserie-1191": { "en": "Layered perfection requires cold temperatures and patience.", "he": "שלמות השכבות דורשת טמפרטורות קרות וסבלנות." },
    "q-patisserie-1193": { "en": "A well-kneaded dough can hold the CO2 produced by yeast.", "he": "בצק שלוש היטב יכול להחזיק את הפחמן הדו-חמצני שמייצר השמרים." },
    "q-patisserie-1194": { "en": "The dry surface is what forces the air out through the bottom.", "he": "המשטח היבש הוא מה שמאלץ את האוויר לצאת דרך התחתית." },
    "q-patisserie-1195": { "en": "No steam escape means no interior hollow for filling.", "he": "חוסר בריחת אדים פירושו שאין חלל פנימי למילוי." },
    "q-patisserie-1197": { "en": "Keep the ingredients at a temperature that respects the fat.", "he": "שמרו על המרכיבים בטמפרטורה שמכבדת את השומן." },
    "q-patisserie-1199": { "en": "Rushing the heat will turn your custard into scrambled eggs.", "he": "מהירות יתר בחימום תהפוך את הקרם שלכם לחביתה." },
    "q-patisserie-1208": { "en": "A flat, dense, and unappetizing loaf of bread.", "he": "כיכר לחם שטוחה, דחוסה ולא מעוררת תיאבון." },
    "q-patisserie-1209": { "en": "The macarons will spread and crack instead of rising elegantly.", "he": "המקרונים יתפשטו וייסדקו במקום לתפוח באלגנטיות." },
    "q-patisserie-1111": { "en": "Fat is a surfactant that destabilizes the protein film.", "he": "שומן הוא חומר פעיל שטח המערער את יציבות קרום החלבון." },
    "q-patisserie-1212": { "en": "It leads to a 'mealy' crust rather than a flaky one.", "he": "זה מוביל לקרום 'קמחי' במקום קרום פריך דפי." },
    "q-patisserie-1214": { "en": "Protects the heat-sensitive proteins in the egg yolks.", "he": "מגן על החלבונים הרגישים לחום שבחלמוני הביצה." },
    "q-patisserie-1215": { "en": "Interruption of the sucrose crystals is key for texture.", "he": "הפרעת גבישי הסוכרוז היא המפתח למרקם." },
    "q-patisserie-1217": { "en": "This builds the strength needed to support a high fat content.", "he": "זה בונה את החוזק הדרוש לתמיכה בתכולת שומן גבוהה." },
    "q-patisserie-1220": { "en": "Beta crystals are what give chocolate its desirable properties.", "he": "גבישי בטא הם שנותנים לשוקולד את תכונותיו הרצויות." },
    "q-patisserie-1223": { "en": "You'll lack the gluten 'balloon' that traps fermentation gases.", "he": "יחסר לכם 'בלון' הגלוטן הלוכד את גזי התסיסה." },
    "q-patisserie-1228": { "en": "Prevents the fat in the cream from separating from the cocoa mass.", "he": "מונע מהשומן שבשמנת להיפרד ממסת הקקאו." },
    "q-patisserie-1230": { "en": "Expect a grainy, crystallized mess instead of silky syrup.", "he": "צפו לבלגן גרגירי ומגובש במקום סירופ משי." },
    "q-patisserie-1233": { "en": "The tart will lack the 'finished' look of quality patisserie.", "he": "לטארט יחסר המראה ה'מוגמר' של קונדיטוריה איכותית." },
    "q-patisserie-1235": { "en": "Provides the necessary snapping point for gourmet chocolates.", "he": "מספק את נקודת השבירה (Snap) הדרושה לשוקולדים איכותיים." },
    "q-patisserie-1238": { "en": "Without structure, bread cannot achieve lightness or crumb.", "he": "ללא מבנה, לחם אינו יכול להשיג קלילות או מרקם פנימי רצוי." },
    "q-patisserie-1241": { "en": "You may end up with a syrup at the bottom and no foam.", "he": "אתם עלולים לסיים עם סירופ בתחתית וללא קצף." },
    "q-patisserie-1242": { "en": "Crucial for producing short and tender pastry items.", "he": "חיוני לייצור מאפים פריכים ורכים." },
    "q-patisserie-1211": { "en": "Fat inhibits the coagulation of the egg white proteins.", "he": "שומן מעכב את קרישת חלבוני חלבון הביצה." }
};

injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/sports_life.js', sportsBatch7);
