import { injectHints } from './hint_utils.mjs';

const batch10 = {
    "q-israeli_music-2938": { "en": "Think of a legendary artist who also happens to be a great actor.", "he": "חשבו על אמן אגדי שהוא גם שחקן מצוין." },
    "q-israeli_music-2939": { "en": "This artist is known for soulful ballads and a deep voice.", "he": "אמן זה מוכר בזכות בלדות מלאות נשמה וקול עמוק." },
    "q-israeli_music-2940": { "en": "A pioneer of Israeli rock 'n' roll.", "he": "מחלוצי הרוקנרול הישראלי." },
    "q-israeli_music-2941": { "en": "One of the members of the 'Kaveret' group.", "he": "אחד מחברי להקת 'כוורת'." },
    "q-israeli_music-2942": { "en": "He frequently collaborated with Shalom Hanoch.", "he": "הוא שיתף פעולה לעתים קרובות עם שלום חנוך." },
    "q-israeli_music-2943": { "en": "Look for the voice behind 'Sof HaOna'.", "he": "חפשו את הקול שמאחורי 'סוף העונה'." },
    "q-israeli_music-2944": { "en": "This artist's first name means 'lion'.", "he": "שמו הפרטי של האמן הזה פירושו 'אריה'." },
    "q-israeli_music-2945": { "en": "A very influential singer-songwriter from the 70s.", "he": "זמר-יוצר משפיע מאוד משנות ה-70." },
    "q-israeli_music-2946": { "en": "Think of a song about 'Ushik' or 'Sufat Chul'.", "he": "חשבו על שיר על 'עושיק' או 'סופת חול'." },
    "q-israeli_music-2947": { "en": "This band is famous for their humor and complex harmonies.", "he": "הלהקה הזו מפורסמת בהומור ובהרמוניות המורכבות שלה." },
    "q-israeli_music-2948": { "en": "Look for hits like 'Rakevet Laila' or 'Az Lama Li Politika'.", "he": "חפשו להיטים כמו 'רכבת לילה' או 'אז למה לי פוליטיקה'." },
    "q-israeli_music-2949": { "en": "The artist often called 'The King of Israeli Rock'.", "he": "האמן המכונה לעתים 'מלך הרוק הישראלי'." },
    "q-israeli_music-2950": { "en": "The band that gave us 'Sof HaOna'.", "he": "הלהקה שנתנה לנו את 'סוף העונה'." },
    "q-israeli_music-2951": { "en": "A leading alt-rock band from the 90s.", "he": "להקת רוק אלטרנטיבי מובילה משנות ה-90." },
    "q-israeli_music-2952": { "en": "Think of 'Paca Paca' or 'Maka Afora'.", "he": "חשבו על 'פקה פקה' או 'מכה אפורה'." },
    "q-israeli_music-2953": { "en": "A heavy rock band known for high energy and deep lyrics.", "he": "להקת רוק כבד המוכרת באנרגיה גבוהה ומילים עמוקות." },
    "q-israeli_music-2954": { "en": "A versatile performer known for TV and music.", "he": "אמן רב-תחומי המוכר מהטלוויזיה ומהמוזיקה." },
    "q-israeli_music-2955": { "en": "Associated with 'Simanim Shel Ohavim' and 'Inyan Shel Zman'.", "he": "מזוהה עם 'סימנים של אוהבים' ו'עניין של זמן'." },
    "q-israeli_music-2956": { "en": "Think of a song about a 'San Remo' or a child's toy.", "he": "חשבו על שיר על 'סן רמו' או צעצוע של ילד." },
    "q-israeli_music-2957": { "en": "Often performs with an acoustic guitar.", "he": "מופיע לעתים קרובות עם גיטרה אקוסטית." },
    "q-israeli_music-2958": { "en": "A band associated with the Florentin neighborhood.", "he": "להקה המזוהה עם שכונת פלורנטין." },
    "q-israeli_music-2959": { "en": "Check for 'Holat Ahava' or similar titles.", "he": "חפשו את 'חולת אהבה' או שמות דומים." },
    "q-israeli_music-2960": { "en": "Songs from the album 'Sippurei Poogy'.", "he": "שירים מהאלבום 'סיפורי פוגי'." },
    "q-israeli_music-2966": { "en": "This album title mentions a type of monster or a big animal.", "he": "שם האלבום הזה מזכיר סוג של מפלצת או חיה גדולה." },
    "q-israeli_music-2967": { "en": "Look for an album from the mid-80s.", "he": "חפשו אלבום מאמצע שנות ה-80." },
    "q-israeli_music-2968": { "en": "The band's breakout album.", "he": "אלבום הפריצה של הלהקה." },
    "q-israeli_music-2969": { "en": "Their third studio album.", "he": "אלבום האולפן השלישי שלהם." },
    "q-israeli_music-2970": { "en": "Named after a famous movie character or machine.", "he": "נקרא על שם דמות קולנועית מפורסמת או מכונה." },
    "q-israeli_music-2971": { "en": "A title related to a 'big monster'.", "he": "שם הקשור ל'מפלצת גדולה'." },
    "q-israeli_music-2972": { "en": "Released in 1988.", "he": "שוחרר בשנת 1988." },
    "q-israeli_music-2973": { "en": "Think of 'Ladies and Gentlemen'.", "he": "חשבו על 'גבירותיי ורבותיי'." },
    "q-israeli_music-2974": { "en": "An album with 'Monster' in the name.", "he": "אלבום עם 'מפלצת' בשם." },
    "q-israeli_music-2975": { "en": "Their 1990 release.", "he": "האלבום שלהם משנת 1990." },
    "q-israeli_music-2976": { "en": "Look for 'Miflatzot HaTehila'.", "he": "חפשו את 'מפלצות התהילה'." },
    "q-israeli_music-2977": { "en": "Released in the mid-90s.", "he": "שוחרר באמצע שנות ה-90." },
    "q-israeli_music-2978": { "en": "The album 'Peak' in Hebrew.", "he": "האלבום 'שיא' בעברית." },
    "q-israeli_music-2979": { "en": "Something about 'Goodbye'.", "he": "משהו על 'להתראות'." },
    "q-israeli_music-2980": { "en": "Their last studio album before the first breakup.", "he": "אלבום האולפן האחרון שלהם לפני הפירוק הראשון." },
    "q-israeli_music-2981": { "en": "A 1995 release.", "he": "שוחרר בשנת 1995." },
    "q-israeli_music-2982": { "en": "A live performance recording.", "he": "הקלטה של הופעה חיה." },
    "q-israeli_music-2983": { "en": "Their unplugged session.", "he": "הסשן האנפלאגד שלהם." },
    "q-israeli_music-2984": { "en": "A return to rock in 2003.", "he": "חזרה לרוק בשנת 2003." },
    "q-israeli_music-2985": { "en": "Released during their second reunion.", "he": "שוחרר במהלך האיחוד השני שלהם." },
    "q-israeli_music-2986": { "en": "Their newest studio work.", "he": "עבודת האולפן החדשה ביותר שלהם." },
    "q-israeli_music-2987": { "en": "The 2000s era.", "he": "תקופת שנות ה-2000." },
    "q-israeli_music-2988": { "en": "Look for 'Romantika Atidit'.", "he": "חפשו את 'רומנטיקה עתידנית'." },
    "q-israeli_music-2989": { "en": "Albums released after 2010.", "he": "אלבומים ששוחררו אחרי 2010." },
    "q-israeli_music-2990": { "en": "The current decade.", "he": "העשור הנוכחי." },
    "q-israeli_music-3041": { "en": "Associated with 'Waiting for Messi' or similar vibes.", "he": "מזוהה עם 'לחכות למשיח' או אווירה דומה." },
    "q-israeli_music-3042": { "en": "A giant of Israeli culture, often wore a simple T-shirt.", "he": "ענק של התרבות הישראלית, לבש לעתים קרובות חולצת טי פשוטה." },
    "q-israeli_music-3043": { "en": "A band that broke all records in the 70s.", "he": "להקה ששברה את כל השיאים בשנות ה-70." },
    "q-israeli_music-3044": { "en": "Look for the album 'Radio Hazak'.", "he": "חפשו את האלבום 'רדיו חזק'." },
    "q-israeli_music-3045": { "en": "A female artist with a powerful voice.", "he": "אמנית בעלת קול עוצמתי." },
    "q-israeli_music-3046": { "en": "The 'Queen of Israeli Pop' in the 80s.", "he": "מלכת הפופ הישראלי בשנות ה-80." },
    "q-israeli_music-3047": { "en": "Associated with Mediterranean rock.", "he": "מזוהה עם רוק ים-תיכוני." },
    "q-israeli_music-3048": { "en": "A rapper who changed the game in the 2000s.", "he": "ראפר ששינה את חוקי המשחק בשנות ה-2000." },
    "q-israeli_music-3049": { "en": "Think of 'Efer VeAvak'.", "he": "חשבו על 'אפר ואבק'." },
    "q-israeli_music-3050": { "en": "A soulful singer from the Black Hebrew community.", "he": "זמרת נשמה מקהילת העבריים מדימונה." },
    "q-israeli_music-3051": { "en": "The artist who sang 'Olat Chozeret'.", "he": "האמן ששר את 'עולה חוזרת'." },
    "q-israeli_music-3052": { "en": "A world-renowned electronic duo.", "he": "צמד אלקטרוני בעל שם עולמי." },
    "q-israeli_music-3053": { "en": "A classic about a 'Red Sweater'.", "he": "קלאסיקה על 'סוודר אדום'." },
    "q-israeli_music-3054": { "en": "Think of 'Ani VeAta'.", "he": "חשבו על 'אני ואתה'." },
    "q-israeli_music-3055": { "en": "She sang 'Hallelujah'.", "he": "היא שרה את 'הללויה'." },
    "q-israeli_music-3056": { "en": "A song about 'Jerusalem of Gold'.", "he": "שיר על 'ירושלים של זהב'." },
    "q-israeli_music-3057": { "en": "Think of the 'Balkan' sound.", "he": "חשבו על הצליל ה'בלקני'." },
    "q-israeli_music-3058": { "en": "A very famous Eurovision winner.", "he": "זוכה אירוויזיון מפורסם מאוד." },
    "q-israeli_music-3059": { "en": "The diva of the 80s and 90s.", "he": "הדיווה של שנות ה-80 וה-90." },
    "q-israeli_music-3060": { "en": "His first name means 'hope'.", "he": "שמו הפרטי פירושו 'תקווה'." },
    "q-movies-3261": { "en": "He's big, green, and lives in a swamp.", "he": "הוא גדול, ירוק וחי בביצה." },
    "q-movies-3263": { "en": "A loud animal that never stops talking.", "he": "חיה רעשנית שלעולם לא מפסיקה לדבר." },
    "q-movies-3264": { "en": "He has a pointy nose and wants to steal the moon.", "he": "יש לו אף מחודד והוא רוצה לגנוב את הירח (גרו)." },
    "q-movies-3265": { "en": "Think of the color of a banana.", "he": "חשבו על הצבע של בננה." },
    "q-movies-3267": { "en": "The King of the Jungle (in Central Park).", "he": "מלך הג'ונגל (בסנטרל פארק)." },
    "q-movies-3268": { "en": "His name is Marty.", "he": "קוראים לו מרטי." },
    "q-movies-3271": { "en": "An acorn is his only goal.", "he": "בלוט הוא המטרה היחידה שלו." },
    "q-movies-3272": { "en": "His name is Sid.", "he": "קוראים לו סיד." },
    "q-movies-3273": { "en": "It's a Night Fury.", "he": "זה 'זעם לילי' (Night Fury)." },
    "q-movies-3279": { "en": "His name starts with B.", "he": "השם שלו מתחיל ב-ב' (ברונו)." },
    "q-movies-3280": { "en": "It's a golden flower with a sun in the middle.", "he": "זהו פרח זהוב עם שמש במרכזו." },
    "q-movies-3281": { "en": "His name is Pascal.", "he": "קוראים לו פסקל." },
    "q-movies-3282": { "en": "She's a small police officer with long ears.", "he": "היא שוטרת קטנה עם אוזניים ארוכות (ארנבת)." },
    "q-movies-3283": { "en": "The slowest animal you can imagine.", "he": "החיה הכי איטית שאתם יכולים לדמיין (עצלנים)." },
    "q-movies-3288": { "en": "A place with massive waterfalls in South America.", "he": "מקום עם מפלים אדירים בדרום אמריקה (מפלי גן עדן)." },
    "q-movies-3289": { "en": "A very tall, colorful, and flightless bird.", "he": "ציפור גדולה מאוד, צבעונית ולא עפה." },
    "q-movies-3290": { "en": "He cleans up all the garbage on Earth.", "he": "הוא מנקה את כל האשפה על כדור הארץ (רובוט)." },
    "q-movies-3295": { "en": "P. Sherman, 42 Wallaby Way, Sydney.", "he": "פי שרמן, וולאבי 42, סידני." },
    "q-movies-3297": { "en": "His name is Miles.", "he": "קוראים לו מיילס (מיילס מוראלס)." },
    "q-movies-3300": { "en": "A giant fish hook.", "he": "קרס דייג ענק." },
    "q-movies-3301": { "en": "A colorful celebration of ancestors.", "he": "חגיגה צבעונית של זיכרון אבות (יום המתים)." },
    "q-movies-3302": { "en": "The movie is named after her.", "he": "הסרט קרוי על שמה (קוקו)." },
    "q-movies-3305": { "en": "Her name starts with S (Sarabi).", "he": "השם שלה מתחיל ב-ס' (סאראבי)." },
    "q-movies-3306": { "en": "No worries for the rest of your days.", "he": "אל דאגה לכל יתר הימים." },
    "q-movies-3307": { "en": "His name is Chip.", "he": "קוראים לו צ'יפ (צ'יפ)." },
    "q-movies-3308": { "en": "A place that is 'Far Far Away'.", "he": "מקום שהוא 'הרחק הרחק מכאן'." },
    "q-movies-3309": { "en": "A very ordinary guy named Emmet.", "he": "בחור רגיל מאוד בשם אמט." },
    "q-general-2272": { "en": "Think of puddles disappearing on a hot day.", "he": "חשבו על שלוליות שנעלמות ביום חם." },
    "q-general-2273": { "en": "Two names, starting with A and B.", "he": "שני שמות, מתחילים ב-א' וב-ב' (אלכסנדר בל)." },
    "q-general-2274": { "en": "The most northern and snowy state.", "he": "המדינה הכי צפונית ומושלגת." },
    "q-general-2275": { "en": "A majestic eagle with a white head.", "he": "עיט מרשים עם ראש לבן (עיטם לבן-ראש)." },
    "q-general-2276": { "en": "It shares the country's name prefix (Brasilia).", "he": "השם דומה מאוד לשם המדינה (ברזיליה)." }
};

injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/culture_ent.js', batch10);
// Additional files for Batch 10
injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/general.js', batch10);
