import { injectHints } from './hint_utils.mjs';

const judaismL3_100 = {
    "q-judaism-37": { "en": "His name is the same as the book he is in.", "he": "שמו כשם הספר שבו הוא מופיע." },
    "q-judaism-44": { "en": "She came from a country in the South to see his wealth and wisdom.", "he": "היא באה ממדינה בדרום כדי לראות את עושרו וחכמתו." },
    "q-judaism-45": { "en": "One is in the North and the other in the South, where Jerusalem is.", "he": "אחת בצפון והשנייה בדרום, איפה שירושלים נמצאת." },
    "q-judaism-46": { "en": "A short name, starting with A.", "he": "שם קצר, מתחיל ב-א'." },
    "q-judaism-48": { "en": "He didn't walk up, he was carried by a fiery vehicle.", "he": "הוא לא עלה ברגל, הוא נישא על ידי רכב אש." },
    "q-judaism-56": { "en": "His name rhymes with 'Hope' in English.", "he": "איש תם וישר, ירא אלוהים וסר מרע." },
    "q-judaism-57": { "en": "He was a cupbearer to the king before returning to Jerusalem.", "he": "הוא היה שר המשקים של המלך לפני שחזר לירושלים." },
    "q-judaism-58": { "en": "He is one of the three major prophets.", "he": "הוא אחד משלושת הנביאים הגדולים." },
    "q-judaism-59": { "en": "The Hebrew name of this book is 'Tehillim'.", "he": "שם הספר הזה בעברית הוא 'תהילים'." },
    "q-judaism-64": { "en": "Think about who brought a gift from the soil.", "he": "חשבו מי הביא מנחה מפרי האדמה." },
    "q-judaism-65": { "en": "This is a negative version of the previous question.", "he": "זו גרסה הפוכה לשאלה הקודמת." },
    "q-judaism-67": { "en": "The oldest person was actually Methuselah.", "he": "האדם המבוגר ביותר היה בעצם מתושלח." },
    "q-judaism-70": { "en": "The change involved adding a 'Hay' (H).", "he": "השינוי כלל הוספת האות ה'." },
    "q-judaism-72": { "en": "She thought it was impossible at her age.", "he": "היא חשבה שזה בלתי אפשרי בגילה." },
    "q-judaism-73": { "en": "She was happy and laughed.", "he": "היא הייתה שמחה וצחקה." },
    "q-judaism-75": { "en": "One was a 'man of the field' and the other 'sat in tents'.", "he": "אחד היה 'איש שדה' והשני 'יושב אוהלים'." },
    "q-judaism-77": { "en": "This is a well-known miracle/event in the Book of Genesis.", "he": "זהו אירוע מפורסם בספר בראשית." },
    "q-judaism-79": { "en": "Israel became his name and the name of the nation.", "he": "ישראל הפך לשמו ולשם האומה." },
    "q-judaism-80": { "en": "Twelve of them bowed down in his dream.", "he": "שנים עשר מהם השתחוו לו בחלומו." },
    "q-judaism-83": { "en": "This set the stage for Joseph's rise in Egypt.", "he": "זה הכין את הקרקע לעלייתו של יוסף במצרים." },
    "q-judaism-84": { "en": "His sister watched from a distance.", "he": "אחותו צפתה מרחוק." },
    "q-judaism-86": { "en": "This happened on Mount Horeb.", "he": "זה קרה בהר חורב." },
    "q-judaism-87": { "en": "The bush was NOT consumed.", "he": "הסנה לא נאכל." },
    "q-judaism-88": { "en": "This was a punishment to make their work harder.", "he": "זה היה עונש כדי להקשות על עבודתם." },
    "q-judaism-89": { "en": "They were indeed forced.", "he": "הם אכן אולצו." },
    "q-judaism-95": { "en": "God told him to speak to the rock, not strike it.", "he": "אלוהים אמר לו לדבר אל הסלע, לא להכות אותו." },
    "q-judaism-97": { "en": "She lived in Jericho and helped the spies.", "he": "היא גרה ביריחו ועזרה למרגלים." },
    "q-judaism-98": { "en": "The water stopped as soon as their feet touched it.", "he": "המים נעצרו ברגע שרגליהם נגעו בהם." },
    "q-judaism-101": { "en": "A sign of wetness and dryness.", "he": "סימן של רטיבות ויובש." },
    "q-judaism-102": { "en": "He was a Nazirite with great strength.", "he": "הוא היה נזיר בעל כוח רב." },
    "q-judaism-103": { "en": "The Bible mentions a lion, not a bear.", "he": "התנ\"ך מזכיר אריה, לא דוב." },
    "q-judaism-106": { "en": "He thought the priest Eli was calling him.", "he": "הוא חשב שהכהן עלי קורא לו." },
    "q-judaism-110": { "en": "He refused to harm 'God's anointed'.", "he": "הוא סירב לפגוע ב'משיח ה''." },
    "q-judaism-111": { "en": "David was merciful.", "he": "דוד היה רחום." },
    "q-judaism-112": { "en": "He is traditionally credited with these three.", "he": "נהוג לייחס לו את שלושתם." },
    "q-judaism-115": { "en": "This happened on Mount Carmel.", "he": "זה קרה בהר הכרמל." },
    "q-judaism-117": { "en": "He was a commander who became king and wiped out the house of Ahab.", "he": "הוא היה מפקד שהפך למלך והשמיד את בית אחאב." },
    "q-judaism-119": { "en": "He was skeptical but his servants convinced him to try.", "he": "הוא היה סקפטי אבל משרתיו שוכנעו אותו לנסות." },
    "q-judaism-224": { "en": "It is named after a man who was assassinated.", "he": "הוא קרוי על שם אדם שנרצח." },
    "q-judaism-225": { "en": "Cheesecakes and blintzes are popular.", "he": "עוגות גבינה ובלינצ'ס פופולריים." },
    "q-judaism-226": { "en": "The name starts with Ch.", "he": "השם מתחיל בח'." },
    "q-judaism-227": { "en": "We ask for it so the plants can grow.", "he": "אנחנו מבקשים אותו כדי שהצמחים יוכלו לצמוח." },
    "q-judaism-228": { "en": "It's a count that starts on the second night of Passover.", "he": "זו ספירה שמתחילה בלילה השני של פסח." },
    "q-judaism-229": { "en": "The 33rd day of the count.", "he": "היום ה-33 לספירה." },
    "q-judaism-240": { "en": "It represents the new home being built.", "he": "היא מייצגת את הבית החדש שנבנה." },
    "q-judaism-241": { "en": "The name rhymes with 'Chutbah'.", "he": "השם מתחרז עם 'כתובה'." },
    "q-judaism-242": { "en": "The name starts with M.", "he": "השם מתחיל במ'." },
    "q-judaism-243": { "en": "Required for a full prayer service.", "he": "נדרש לתפילה מלאה." },
    "q-judaism-244": { "en": "When a marriage legally ends.", "he": "כאשר נישואין מסתיימים באופן חוקי." },
    "q-judaism-252": { "en": "The 'explanation' part of the Talmud.", "he": "חלק ה'הסבר' של התלמוד." },
    "q-judaism-253": { "en": "Also known by the acronym Rambam.", "he": "ידוע גם בראשי התיבות רמב\"ם." },
    "q-judaism-254": { "en": "Recited by those who have lost a loved one.", "he": "נאמר על ידי מי שאיבד אדם יקר." },
    "q-judaism-263": { "en": "Related to the word for Germany in Hebrew.", "he": "קשור למילה 'אשכנז'." },
    "q-judaism-264": { "en": "Related to the word for Spain in Hebrew.", "he": "קשור למילה 'ספרד'." },
    "q-judaism-265": { "en": "A symbol of Jewish heroism and the last stand.", "he": "סמל לגבורה יהודית ולעמידה האחרונה." },
    "q-judaism-266": { "en": "Found in Qumran.", "he": "נמצאו בקומראן." },
    "q-judaism-267": { "en": "His last name is Ben-Yehuda.", "he": "שם משפחתו הוא בן-יהודה." },
    "q-judaism-268": { "en": "The name means 'Reception' or 'Tradition'.", "he": "השם פירושו 'מסורת' או 'קבלה'." },
    "q-judaism-274": { "en": "It looks like bricks and mortar.", "he": "זה נראה כמו לבנים וטיט." },
    "q-judaism-276": { "en": "A word starting with D.", "he": "מילה המתחילה בד'." },
    "q-judaism-279": { "en": "A seven-day period.", "he": "תקופה של שבעה ימים." },
    "q-judaism-280": { "en": "A German/Yiddish word for 'Year time'.", "he": "מילה ביידיש שפירושה 'זמן שנה'." },
    "q-judaism-284": { "en": "Milk and Meat products.", "he": "מוצרי חלב ובשר." },
    "q-judaism-285": { "en": "The blessing over 'fruit of the vine'.", "he": "הברכה על 'פרי הגפן'." },
    "q-judaism-286": { "en": "The blessing for food 'from the earth'.", "he": "הברכה על אוכל שיוצא 'מן הארץ'." },
    "q-judaism-287": { "en": "The stage for reading the Torah.", "he": "הבמה לקריאת התורה." },
    "q-judaism-288": { "en": "A light that is never turned off.", "he": "אור שמעולם לא כובה." },
    "q-judaism-293": { "en": "A song that starts with A.", "he": "שיר שמתחיל ב-א'." },
    "q-judaism-294": { "en": "Like the kohanim in the temple.", "he": "כמו הכהנים במקדש." },
    "q-judaism-295": { "en": "The name means 'to cast away'.", "he": "חלק ממנהג ימי התשובה." },
    "q-judaism-296": { "en": "A month of repentance before the High Holidays.", "he": "חודש של תשובה לפני החגים הנוראים." },
    "q-judaism-297": { "en": "The 15th of the month of Av.", "he": "ט\"ו באב." },
    "q-judaism-298": { "en": "It starts when the sun goes down.", "he": "הוא מתחיל כשהשמש שוקעת." },
    "q-judaism-299": { "en": "Symbols like honey and pomegranate.", "he": "סמלים כמו דבש ורימון." },
    "q-judaism-300": { "en": "It is the blueprint for Jewish life.", "he": "זוהי תוכנית האב לחיים היהודיים." },
    "q-judaism-301": { "en": "Taryag in Hebrew letters.", "he": "תרי\"ג בגימטריה." },
    "q-judaism-302": { "en": "Yes, it is true.", "he": "כן, זה נכון." },
    "q-judaism-303": { "en": "A place for gathering.", "he": "מקום התכנסות." },
    "q-judaism-304": { "en": "The four-fringed garment.", "he": "בגד ארבע כנפות." },
    "q-judaism-305": { "en": "Giving to those in need.", "he": "נתינה לנזקקים." },
    "q-judaism-306": { "en": "The focal point during Torah reading.", "he": "מרכז תשומת הלב בזמן קריאת התורה." },
    "q-judaism-307": { "en": "A distinct typeface used for his commentary.", "he": "גופן מיוחד המשמש לפירושיו." },
    "q-judaism-308": { "en": "Divided into many books.", "he": "מחולק להרבה ספרים." },
    "q-judaism-309": { "en": "A movement focused on joy and prayer.", "he": "תנועה המתמקדת בשמחה ובתפילה." },
    "q-judaism-2781": { "en": "Commonly known as the Law of the Jews.", "he": "מכונה בדרך כלל משפט העברים." },
    "q-judaism-2782": { "en": "The father of Issac and Ishmael.", "he": "אביהם של יצחק וישמעאל." },
    "q-judaism-2783": { "en": "The establishment of the State of Israel.", "he": "הקמת מדינת ישראל." },
    "q-judaism-2785": { "en": "Related to the generations of the desert.", "he": "קשור לדור המדבר." },
    "q-judaism-2788": { "en": "He was the wise son of King David.", "he": "הוא היה בנו החכם של המלך דוד." },
    "q-judaism-2789": { "en": "Center stage in the synagogue.", "he": "מרכז הבמה בבית הכנסת." },
    "q-judaism-2808": { "en": "Jerusalem and Babylon versions.", "he": "גרסאות ירושלים ובבל." },
    "q-judaism-2809": { "en": "The first month of the Hebrew calendar year in the Bible.", "he": "החודש הראשון בלוח השנה העברי בתנ\"ך." },
    "q-judaism-2810": { "en": "He was anointed by Samuel.", "he": "הוא נמשח על ידי שמואל." },
    "q-judaism-2812": { "en": "Ancient city in the Judean Hills.", "he": "עיר עתיקה בהרי יהודה." },
    "q-judaism-2813": { "en": "Famous for the fire from heaven on Mount Carmel.", "he": "מפורסם בזכות האש מהשמיים בהר הכרמל." }
};

injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/judaism.js', judaismL3_100);
