import { injectHints } from './hint_utils.mjs';

const batch11 = {
    "q-general-2277": { "en": "She was known as 'The Lady with the Lamp'.", "he": "היא הייתה ידועה כ'הגברת עם המנורה'." },
    "q-general-2278": { "en": "It's the first element on the periodic table.", "he": "זהו היסוד הראשון בטבלה המחזורית (מימן)." },
    "q-animals-1506": { "en": "A giant sea creature that lives in the deep ocean.", "he": "יצור ים ענק שחי במעמקי האוקיינוס (דיונון ענק)." },
    "q-animals-1507": { "en": "The name sounds like something very bright and intense.", "he": "השם נשמע כמו משהו בוער ואינטנסיבי (Flamboyance)." },
    "q-animals-1508": { "en": "An marine mammal like a whale or a seal.", "he": "יונק ימי כמו לווייתן או כלב ים (לווייתן מקור סוברבי)." },
    "q-animals-1509": { "en": "They don't have traditional teeth, but they have 47 'sharp tools'.", "he": "אין להם שיניים רגילות, אלא 47 'כלי חיתוך' חדים." },
    "q-animals-1510": { "en": "A very small, colorful bird that hums.", "he": "ציפור קטנה וצבעונית שמשמיעה זמזום (קוליברי)." },
    "q-animals-1659": { "en": "Found on the Rock of Gibraltar.", "he": "נמצא על צוק גיברלטר (מקוק ברברי)." },
    "q-animals-1660": { "en": "Think of the ones that look most like humans.", "he": "חשבו על אלו שהכי דומים לבני אדם (שימפנזים או בונובו)." },
    "q-animals-1661": { "en": "The name starts with P.", "he": "השם מתחיל ב-פ' (פרימטים)." },
    "q-animals-1662": { "en": "Compare with monkeys; apes don't have tails.", "he": "השוו לקופים; לקופי אדם אין זנב." },
    "q-animals-1663": { "en": "They are known for being very peaceful and social.", "he": "הם ידועים כחברותיים ודיפלומטיים מאוד." },
    "q-animals-1664": { "en": "Think of the Mandrill or Vervet monkey.", "he": "חשבו על המנדריל או קוף הוורבט." },
    "q-animals-1665": { "en": "Comes from the word 'Primate'.", "he": "מגיע מהמילה 'פרימט' (פרימטולוגיה)." },
    "q-animals-1666": { "en": "Look for the Mandrill.", "he": "חפשו את המנדריל." },
    "q-animals-1667": { "en": "It's called a 'prehensile' tail.", "he": "זה נקרא זנב לופת (Prehensile)." },
    "q-animals-1668": { "en": "Think of Colobus or Langur monkeys.", "he": "חשבו על קופי הקולובוס או הלנגור." },
    "q-animals-1669": { "en": "They are arboreal animals.", "he": "הם בעלי חיים שוכני עצים." },
    "q-animals-1670": { "en": "Found only on the island of Sumatra.", "he": "נמצא רק באי סומטרה (אורנגאוטן סומטרה)." },
    "q-animals-1671": { "en": "The tiny Tarsier.", "he": "הקיפוף הזעיר (טרסייר)." },
    "q-animals-1672": { "en": "The same as humans: 2-1-2-3.", "he": "כמו אצל בני אדם: 2-1-2-3." },
    "q-animals-1673": { "en": "They use it for social bonding.", "he": "הם משתמשים בזה לחיזוק קשרים חברתיים (פוליטיקה של שימפנזים)." },
    "q-animals-1674": { "en": "Deforestation for palm oil.", "he": "בירוא יערות עבור שמן דקלים." },
    "q-animals-1675": { "en": "Check for the Proboscis monkey.", "he": "חפשו את קוף החוטם." },
    "q-animals-1676": { "en": "It's a way of moving called brachiation.", "he": "זו דרך תנועה הנקראת 'ברכיאציה' (התנדנדות)." },
    "q-animals-1677": { "en": "The name tells you when it's active.", "he": "השם אומר לכם מתי הוא פעיל (בלילה)." },
    "q-animals-1678": { "en": "Think of Spider monkeys.", "he": "חשבו על קופי עכביש." },
    "q-nature-2149": { "en": "It's a type of swift.", "he": "זה סוג של סיס (סיס זנב-קוץ)." },
    "q-nature-2150": { "en": "A massive fungus in Oregon.", "he": "פטרייה עצומה במדינת אורגון (ארמילאריה)." },
    "q-nature-2153": { "en": "A shield volcano in Hawaii.", "he": "הר געש מגן בהוואי (מאונה לואה)." },
    "q-nature-2154": { "en": "Starts with G.", "he": "מתחיל ב-ג' (גנימד)." },
    "q-nature-2155": { "en": "Measured during a tropical cyclone.", "he": "נמדד במהלך סופה טרופית (מעל 400 קמ\"ש)." },
    "q-nature-2156": { "en": "The Japanese spider crab.", "he": "סרטן העכביש היפני." },
    "q-nature-2157": { "en": "The Coco de Mer.", "he": "קוקוס הים (קוקו דה מר)." },
    "q-nature-2158": { "en": "The Shortfin Mako.", "he": "ענתוש קצר-סנפיר (מאקו)." },
    "q-nature-2159": { "en": "The Milwaukee Deep.", "he": "תהום מילווקי." },
    "q-nature-2160": { "en": "Don't think of the Dead Sea; look for Don Juan Pond.", "he": "אל תחשבו על ים המלח; חפשו את בריכת דון חואן." },
    "q-nature-2161": { "en": "Mount Vinson.", "he": "הר וינסון." },
    "q-nature-2162": { "en": "Located in Hawaii.", "he": "נמצא בהוואי (קילוואה)." },
    "q-nature-2163": { "en": "The Giraffe has to pump blood all the way up its neck.", "he": "לג'ירפה יש צורך להזרים דם במעלה הצוואר הארוך." },
    "q-nature-2164": { "en": "Colossal Squid.", "he": "דיונון קולוסאלי." },
    "q-nature-2165": { "en": "Etruscan shrew.", "he": "חדף זעיר (Etruscan shrew)." },
    "q-nature-2166": { "en": "Green Anaconda.", "he": "אנקונדה ירוקה." },
    "q-human_body-2631": { "en": "It's the thigh bone.", "he": "זוהי עצם הירך (פמור)." },
    "q-human_body-2632": { "en": "These cells are shaped like objects used in road traffic.", "he": "התאים האלו מעוצבים כמו חרוטים (מדוכים - Cones)." },
    "q-human_body-2633": { "en": "Thirty-something.", "he": "שלושים וכמה (33)." },
    "q-human_body-2634": { "en": "Starts with M.", "he": "מתחיל ב-מ' (מלנין)." },
    "q-human_body-2635": { "en": "At the base of the brain.", "he": "בבסיס המוח." },
    "q-human_body-2636": { "en": "Also found in milk.", "he": "נמצא גם בחלב (סידן)." },
    "q-human_body-2637": { "en": "The pancreas produces insulin for this.", "he": "הלבלב מייצר אינסולין למטרה זו." },
    "q-human_body-2638": { "en": "Cerebrospinal fluid.", "he": "נוזל המוח והשדרה (CSF)." },
    "q-human_body-2639": { "en": "Starts with H.", "he": "מתחיל ב-ה' (המוגלובין)." },
    "q-human_body-2640": { "en": "Between 4 and 6.", "he": "בין 4 ל-6 (כ-5 ליטרים)." },
    "q-human_body-2641": { "en": "Epiglottis.", "he": "מכסה הגרון (אפיגלוטיס)." },
    "q-human_body-2642": { "en": "Contains three fluid-filled loops.", "he": "מכיל שלוש לולאות מלאות נוזל." },
    "q-human_body-2643": { "en": "Starts with M.", "he": "מתחיל ב-מ' (מיטוזה)." },
    "q-human_body-2644": { "en": "It's type O.", "he": "סוג דם O." },
    "q-human_body-2645": { "en": "The Liver.", "he": "הכבד." },
    "q-human_body-2646": { "en": "The Mitral or Bicuspid valve.", "he": "המסתם המיטרלי (או הדו-צניפי)." },
    "q-human_body-2647": { "en": "The Nephron.", "he": "הנפרון." },
    "q-human_body-2648": { "en": "Inside the bones.", "he": "בתוך העצמות (מוח העצם)." },
    "q-human_body-2649": { "en": "Hyperglycemia.", "he": "היפרגליקמיה." },
    "q-human_body-2650": { "en": "The Olfactory nerve.", "he": "עצב הריח (אולפקטורי)." },
    "q-human_body-2681": { "en": "The Aorta.", "he": "אבי העורקים (אאורטה)." },
    "q-human_body-2682": { "en": "Keratin protein.", "he": "חלבון קרטין." },
    "q-human_body-2683": { "en": "The upper arm.", "he": "הזרוע העליונה." },
    "q-human_body-2684": { "en": "Plasma.", "he": "פלזמה." },
    "q-human_body-2685": { "en": "The Liver is the body's filter.", "he": "הכבד הוא המסנן של הגוף." },
    "q-human_body-2686": { "en": "The Diaphragm.", "he": "הסרעפת." },
    "q-human_body-2687": { "en": "Twenty-three.", "he": "עשרים ושלושה (23)." },
    "q-human_body-2688": { "en": "The Larynx.", "he": "לרינקס." },
    "q-human_body-2689": { "en": "Sensory neurons.", "he": "נוירון תחושתי (סנסורי)." },
    "q-human_body-2690": { "en": "The Epiglottis.", "he": "מכסה הגרון (אפיגלוטיס)." },
    "q-human_body-2691": { "en": "In the middle ear.", "he": "באוזן התיכונה (שריר המשוורת)." },
    "q-human_body-2692": { "en": "The Masseter (jaw muscle).", "he": "שריר המלעס (בלסת)." },
    "q-human_body-2693": { "en": "The Pancreas.", "he": "הלבלב." },
    "q-human_body-2694": { "en": "The Fibula.", "he": "השוקית (פיבולה)." },
    "q-human_body-2695": { "en": "Detecting rotation and movement.", "he": "זיהוי סיבוב ותנועה." },
    "q-human_body-2696": { "en": "The Cerebrum.", "he": "המוח הגדול (צרברום)." },
    "q-human_body-2697": { "en": "A Stethoscope.", "he": "סטטוסקופ." },
    "q-human_body-2698": { "en": "The Liver.", "he": "הכבד." },
    "q-human_body-2699": { "en": "A Synapse.", "he": "סינפסה." },
    "q-human_body-2700": { "en": "Myoglobin.", "he": "מיוגלובין." },
    "q-math-776": { "en": "Just add the tens.", "he": "פשוט הוסיפו את העשרות." },
    "q-math-779": { "en": "Add 40 and then another 5.", "he": "הוסיפו 40 ואז עוד 5." },
    "q-math-782": { "en": "Think of 60+30 and then add the units.", "he": "חשבו על 60+30 ואז הוסיפו את היחידות." },
    "q-math-785": { "en": "Double 24.", "he": "פעמיים 24." },
    "q-math-788": { "en": "60 and 10 and 2+8.", "he": "60 ועוד 10 ועוד 2+8." },
    "q-math-791": { "en": "Just increase the tens digit by 1.", "he": "פשוט הגדילו את ספרת העשרות ב-1." },
    "q-math-794": { "en": "Almost 50+50.", "he": "כמעט 50+50." },
    "q-math-797": { "en": "Add 10 and then 4.", "he": "הוסיפו 10 ואז 4." },
    "q-math-800": { "en": "Exceeds 100.", "he": "זה עובר את ה-100." },
    "q-math-803": { "en": "Add 10 and then 5.", "he": "הוסיפו 10 ואז 5." },
    "q-math-806": { "en": "80+20 + 5+9.", "he": "80+20 ועוד 5+9." },
    "q-math-809": { "en": "Add 10 and then 4.", "he": "הוסיפו 10 ואז 4." },
    "q-math-812": { "en": "Almost 100+47.", "he": "כמעט 100+47." },
    "q-math-815": { "en": "80+30 + 9+3.", "he": "80+30 ועוד 9+3." },
    "q-math-818": { "en": "90+10 + 6+9.", "he": "90+10 ועוד 6+9." },
    "q-math-821": { "en": "Add 30 and then 1.", "he": "הוסיפו 30 ואז 1." },
    "q-math-824": { "en": "70+40 + 7+5.", "he": "70+40 ועוד 7+5." }
};

injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/general.js', batch11);
injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/nature.js', batch11);
injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/science.js', batch11);
