import { injectHints } from './hint_utils.mjs';

const judaismBatch = {
    "q-judaism-10": { "en": "He had to work for many years to marry the woman he loved.", "he": "הוא נאלץ לעבוד שנים רבות כדי לשאת את האישה שאהב." },
    "q-judaism-13": { "en": "A group of traders traveling with camels.", "he": "קבוצת סוחרים הנוסעים עם גמלים." },
    "q-judaism-26": { "en": "The earth opened up and swallowed him and his followers.", "he": "האדמה פצתה את פיה ובלעה אותו ואת פמלייתו." },
    "q-judaism-27": { "en": "A large stone formation.", "he": "מבנה אבן גדול." },
    "q-judaism-32": { "en": "She sat under a palm tree in the hills of Ephraim.", "he": "היא ישבה תחת תומר בהר אפרים." },
    "q-judaism-33": { "en": "A very small number, related to the number of days in a year (roughly).", "he": "מספר קטן מאוד, קשור למערך הלוחמי המצומצם שלו." },
    "q-judaism-2784": { "en": "A major milestone in Jewish history.", "he": "אבן דרך משמעותית בהיסטוריה היהודית." },
    "q-judaism-2786": { "en": "A long period of time, enough for a new generation to grow.", "he": "תקופה ארוכה של זמן, המספיקה לדור חדש לצמוח." },
    "q-judaism-2787": { "en": "Think about the act of choosing.", "he": "חשבו על פעולת הבחירה." },
    "q-judaism-2790": { "en": "A high place for reading.", "he": "מקום גבוה לקריאה." },
    "q-judaism-2811": { "en": "Anointed by Samuel.", "he": "נמשח על ידי שמואל." },
    "q-judaism-2814": { "en": "He lived in the time of King Ahab.", "he": "הוא חי בתקופת המלך אחאב." },
    "q-judaism-2815": { "en": "A year ending in 70.", "he": "שנה המסתיימת ב-70." },
    "q-judaism-2846": { "en": "She led the women in song after crossing the sea.", "he": "היא הובילה את הנשים בשירה לאחר חציית הים." },
    "q-judaism-2847": { "en": "One from each tribe.", "he": "אחד מכל שבט." },
    "q-judaism-2848": { "en": "He led the people into the Promised Land.", "he": "הוא הוביל את העם אל הארץ המובטחת." },
    "q-judaism-2849": { "en": "A prayer of praise.", "he": "תפילת שבח." },
    "q-judaism-2850": { "en": "A symbol of protection on doorposts.", "he": "סמל להגנה על מזוזות הדלת." },
    "q-judaism-2851": { "en": "One year after twelve.", "he": "שנה אחת אחרי שתים עשרה." },
    "q-judaism-2852": { "en": "The age of maturity for girls.", "he": "גיל הבגרות לבנות." },
    "q-judaism-2853": { "en": "A place of study and prayer.", "he": "מקום של לימוד ותפילה." },
    "q-judaism-2854": { "en": "The religious leader of a community.", "he": "המנהיג הדתי של הקהילה." },
    "q-judaism-2855": { "en": "A pointer for reading Torah.", "he": "מצביע לקריאה בתורה." },
    "q-judaism-2856": { "en": "The month of the High Holidays.", "he": "חודש החגים הנוראים." },
    "q-judaism-2857": { "en": "The month of joy.", "he": "חודש השמחה." },
    "q-judaism-2858": { "en": "A light above the Ark.", "he": "אור מעל הארון." },
    "q-judaism-2859": { "en": "It means luck or constellation.", "he": "זה אומר מזל או קונסטלציה." },
    "q-judaism-2860": { "en": "A complete number in many traditions.", "he": "מספר שלם במסורות רבות." },
    "q-judaism-ext-bible-9": { "en": "A fiery ride to heaven.", "he": "נסיעה לוהטת לשמיים." },
    "q-judaism-ext-bible-10": { "en": "He succeeded Moses.", "he": "הוא ירש את משה." },
    "q-judaism-ext-bible-22": { "en": "A small river in the Gilead.", "he": "נהר קטן בגלעד." },
    "q-judaism-ext-bible-25": { "en": "She was a brave woman from the Kenites.", "he": "היא הייתה אישה אמיצה מהקינים." },
    "q-judaism-ext-bible-29": { "en": "They refused to bow to an idol in Babylon.", "he": "הם סירבו להשתחוות לפסל בבבל." },
    "q-judaism-ext-bible-34": { "en": "The final day of the siege.", "he": "היום האחרון של המצור." },
    "q-judaism-ext-bible-36": { "en": "He went up in a storm.", "he": "הוא עלה בסערה." },
    "q-judaism-ext-bible-37": { "en": "A wealthy landowner in Bethlehem.", "he": "בעל קרקעות עשיר בבית לחם." },
    "q-judaism-ext-bible-47": { "en": "A fertile region in Egypt.", "he": "אזור פורה במצרים." },
    "q-judaism-ext-bible-48": { "en": "He witnessed the destruction of Jerusalem.", "he": "הוא היה עד לחורבן ירושלים." },
    "q-judaism-ext-holidays-21": { "en": "A family of warriors.", "he": "משפחה של לוחמים." },
    "q-judaism-ext-holidays-22": { "en": "Making a distinction between sacred and secular.", "he": "עריכת הבחנה בין קודש לחול." },
    "q-judaism-ext-holidays-24": { "en": "Cast away your sins into the water.", "he": "השלך את חטאיך אל המים." },
    "q-judaism-ext-holidays-25": { "en": "The Great Sabbath.", "he": "השבת הגדולה." },
    "q-judaism-ext-holidays-29": { "en": "A vessel with less than the required number of lights.", "he": "כלי עם פחות ממספר הנרות הנדרש." },
    "q-judaism-ext-holidays-32": { "en": "Receiving the Torah.", "he": "קבלת התורה." },
    "q-judaism-ext-holidays-34": { "en": "A blessing once every 28 years.", "he": "ברכה פעם ב-28 שנים." },
    "q-judaism-ext-holidays-40": { "en": "An additional prayer service.", "he": "תפילה נוספת." },
    "q-judaism-ext-holidays-41": { "en": "The story of a convert from Moab.", "he": "סיפורה של גיורת ממואב." },
    "q-judaism-ext-holidays-42": { "en": "Mixing of cooked foods to allow cooking on a holiday for Shabbat.", "he": "ערבוב תבשילים כדי לאפשר בישול בחג לצורך שבת." },
    "q-judaism-ext-holidays-44": { "en": "A symbol of peace.", "he": "סמל לשלום." },
    "q-judaism-ext-holidays-45": { "en": "The day Moses died (traditionally).", "he": "היום שבו מת משה (לפי המסורת)." },
    "q-judaism-ext-holidays-46": { "en": "Redemption of the firstborn son.", "he": "פדיון הבן הבכור." },
    "q-judaism-ext-holidays-48": { "en": "Accompanying the Queen as she departs.", "he": "ליווי המלכה בצאתה." },
    "q-judaism-ext-tradition-11": { "en": "A ceremony for firstborn sons.", "he": "טקס לבנים בכורים." },
    "q-judaism-ext-tradition-16": { "en": "The core text of Rabbinic Judaism.", "he": "טקסט הליבה של היהדות הרבנית." },
    "q-judaism-ext-tradition-20": { "en": "The way of walking or proceeding.", "he": "הדרך ללכת או להתקדם." },
    "q-judaism-ext-tradition-29": { "en": "Separating a portion of dough.", "he": "הפרשת חלק מהבצק." },
    "q-judaism-ext-tradition-31": { "en": "Items that are set aside and cannot be moved.", "he": "פריטים המוקצים ואינם ניתנים להזזה." },
    "q-judaism-ext-tradition-40": { "en": "A prayer of sanctification.", "he": "תפילת קידוש." },
    "q-judaism-ext-tradition-43": { "en": "A professional scribe.", "he": "סופר מקצועי." },
    "q-judaism-ext-tradition-49": { "en": "Milk produced under Jewish supervision.", "he": "חלב המיוצר תחת השגחה יהודית." }
};

const natureBatch = {
    "q-nature-47": { "en": "The highest mountain in the world.", "he": "ההר הגבוה ביותר בעולם." },
    "q-nature-48": { "en": "The longest river in South America.", "he": "הנהר הארוך ביותר בדרום אמריקה." },
    "q-nature-49": { "en": "The largest desert in the world (if you exclude the polar regions).", "he": "המדבר הגדול ביותר בעולם (אם לא כוללים את אזורי הקטבים)." },
    "q-nature-50": { "en": "The largest ocean on Earth.", "he": "האוקיינוס הגדול ביותר על פני כדור הארץ." },
    "q-nature-51": { "en": "The layer of gas that surrounds the Earth.", "he": "שכבת הגז שמקיפה את כדור הארץ." },
    "q-nature-52": { "en": "The process by which plants make their own food.", "he": "התהליך שבו צמחים מייצרים את המזון שלהם." },
    "q-nature-53": { "en": "The force that pulls objects toward the Earth.", "he": "הכוח שמושך חפצים לכיוון כדור הארץ." },
    "q-nature-54": { "en": "The smallest type of bird in the world.", "he": "סוג הציפור הקטן ביותר בעולם." },
    "q-nature-55": { "en": "The only mammal that can fly.", "he": "היונק היחיד שיכול לעוף." },
    "q-nature-56": { "en": "The fastest land animal.", "he": "בעל החיים היבשתי המהיר ביותר." },
    "q-nature-57": { "en": "The largest animal to ever live on Earth.", "he": "בעל החיים הגדול ביותר שחי אי פעם על פני כדור הארץ." },
    "q-nature-58": { "en": "The parts of an insect's body.", "he": "חלקי גופו של חרק." },
    "q-nature-59": { "en": "Animals that live both on land and in water.", "he": "בעלי חיים החיים גם ביבשה וגם במים." },
    "q-nature-60": { "en": "What do we call animals that only eat plants?", "he": "איך קוראים לבעלי חיים שאוכלים רק צמחים?" },
    "q-nature-61": { "en": "What do we call animals that only eat meat?", "he": "איך קוראים לבעלי חיים שאוכלים רק בשר?" },
    "q-nature-62": { "en": "What is the name of the white part of an egg?", "he": "מה השם של החלק הלבן של הביצה?" },
    "q-nature-92": { "en": "The colorful part of a plant's flower.", "he": "החלק הצבעוני של פרח הצמח." },
    "q-nature-93": { "en": "The process of a caterpillar turning into a butterfly.", "he": "התהליך של זחל שהופך לפרפר." },
    "q-nature-94": { "en": "A large community of plants and animals that live in the same area.", "he": "קהילה גדולה של צמחים ובעלי חיים החיים באותו אזור." },
    "q-nature-95": { "en": "The study of living things.", "he": "חקר הדברים החיים." },
    "q-nature-96": { "en": "The natural home or environment of an animal.", "he": "הבית או הסביבה הטבעית של בעל חיים." },
    "q-nature-97": { "en": "When an animal sleeps through the winter.", "he": "כאשר בעל חיים ישן לאורך כל החורף." },
    "q-nature-98": { "en": "The transfer of pollen from one flower to another.", "he": "העברת אבקה מפרח אחד למשנהו." },
    "q-nature-99": { "en": "The breaking of rock into smaller pieces by wind or water.", "he": "שבירת סלע לחתיכות קטנות יותר על ידי רוח או מים." },
    "q-nature-100": { "en": "A large mass of moving ice.", "he": "מסה גדולה של קרח נע." },
    "q-nature-101": { "en": "The remains of a plant or animal from a long time ago.", "he": "שרידים של צמח או בעל חיים מלפני זמן רב." },
    "q-nature-102": { "en": "The sudden shaking of the ground.", "he": "רעידה פתאומית של הקרקע." },
    "q-nature-103": { "en": "An opening in the Earth's crust that spews lava.", "he": "פתח בקרום כדור הארץ שפולט לבה." },
    "q-nature-104": { "en": "A very large wave caused by an underwater earthquake.", "he": "גל גדול מאוד הנגרם על ידי רעידת אדמה תת-ימית." },
    "q-nature-105": { "en": "The invisible line that divides the Earth into North and South.", "he": "הקו הבלתי נראה שמחלק את כדור הארץ לצפון ודרום." },
    "q-nature-106": { "en": "The direction that the needle of a compass points to.", "he": "הכיוון אליו מצביע המחט של המצפן." },
    "q-nature-107": { "en": "The four main directions (North, South, East, West).", "he": "ארבעת הכיוונים העיקריים (צפון, דרום, מזרח, מערב)." },
    "q-nature-108": { "en": "A draw of a part of the Earth's surface.", "he": "ציור של חלק מפני השטח של כדור הארץ." },
    "q-nature-109": { "en": "The book of maps.", "he": "ספר המפות." },
    "q-nature-110": { "en": "A round model of the Earth.", "he": "דגם עגול של כדור הארץ." },
    "q-nature-111": { "en": "Something that is used to tell directions.", "he": "משהו שמשמש לציון כיוונים." },
    "q-nature-112": { "en": "A place where there is very little rain.", "he": "מקום שבו יש מעט מאוד גשם." },
    "q-nature-113": { "en": "A large body of salt water.", "he": "גוף גדול של מים מלוחים." },
    "q-nature-114": { "en": "A large body of fresh water surrounded by land.", "he": "גוף גדול של מים מתוקים המוקף ביבשה." },
    "q-nature-115": { "en": "A flowing body of water.", "he": "גוף מים זורם." }
};

injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/judaism.js', judaismBatch);
injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/nature.js', natureBatch);
