import { injectHints } from './hint_utils.mjs';

const cultureBatch = {
    "q-israeli_music-1398": { "en": "A legendary singer often called 'the voice of the nation'.", "he": "זמרת אגדית המכונה לעיתים 'קול המדינה'." },
    "q-israeli_music-1399": { "en": "A famous show and band from the 1960s.", "he": "מופע ולהקה מפורסמת משנות ה-60." },
    "q-israeli_music-1400": { "en": "He sang 'Aba Sheli' and 'HaYeled HaZe Hu Ani'.", "he": "הוא שר את 'אבא שלי' ו'הילד הזה הוא אני'." },
    "q-israeli_music-1401": { "en": "A rock band led by Berry Sakharof and Rami Fortis (sometimes).", "he": "להקת רוק שבראשה עמדו ברי סחרוף ורמי פורטיס." },
    "q-israeli_music-1402": { "en": "Think about the Eurovision winner with 'Hallelujah'.", "he": "חשבו על זוכת האירוויזיון עם 'הללויה'." },
    "q-israeli_music-1403": { "en": "A very tall singer with a deep voice.", "he": "זמר גבוה מאוד עם קול עמוק." },
    "q-israeli_music-1404": { "en": "She won the Eurovision with 'Toy'.", "he": "היא זכתה באירוויזיון עם השיר 'Toy'." },
    "q-israeli_music-1405": { "en": "A band named after a Mediterranean city.", "he": "להקה הקרויה על שם עיר ים-תיכונית." },
    "q-israeli_music-1406": { "en": "His first name means 'lion' in Hebrew.", "he": "שמו הפרטי פירושו 'אריה'." },
    "q-israeli_music-1407": { "en": "A famous duo consisting of a man and a woman.", "he": "צמד מפורסם המורכב מגבר ואישה." },
    "q-israeli_music-1408": { "en": "A rapper known for his patriotic songs.", "he": "ראפר הידוע בשיריו הפטריוטיים." },
    "q-israeli_music-1409": { "en": "The name of a band that includes Shlomo Artzi (early on).", "he": "שם של להקה שכללה את שלמה ארצי (בתחילת דרכו)." },
    "q-israeli_music-1410": { "en": "A group of singers perform together.", "he": "קבוצת זמרים המופיעה יחד." },
    "q-israeli_music-1411": { "en": "She is known as the 'Queen of Hebrew Song'.", "he": "היא ידועה כ'מלכת הזמר העברי'." },
    "q-israeli_music-1412": { "en": "A band with a very 'sweet' name.", "he": "להקה עם שם 'מתוק' מאוד." },
    "q-israeli_music-1413": { "en": "He sang about 'The Small Prince'.", "he": "הוא שר על 'הנסיך הקטן'." },
    "q-israeli_music-1439": { "en": "A song by Naomi Shemer.", "he": "שיר של נעמי שמר." },
    "q-israeli_music-1440": { "en": "An iconic rock group from the 70s.", "he": "להקת רוק אייקונית משנות ה-70." },
    "q-israeli_music-1441": { "en": "Winner of an international music contest.", "he": "זוכה בתחרות מוזיקה בינלאומית." },
    "q-israeli_music-1442": { "en": "A very successful pop star.", "he": "כוכב פופ מצליח מאוד." },
    "q-israeli_music-1443": { "en": "Related to the Kibbutz movement (often).", "he": "קשור לתנועה הקיבוצית (לרוב)." },
    "q-israeli_music-1444": { "en": "A soul singer with a unique style.", "he": "זמר נשמה עם סגנון ייחודי." },
    "q-israeli_music-1445": { "en": "A band of 'friends'.", "he": "להקה של 'חברים'." },
    "q-israeli_music-1446": { "en": "He has a very famous father in the music industry.", "he": "יש לו אבא מפורסם מאוד בתעשיית המוזיקה." },
    "q-israeli_music-1447": { "en": "A group from the 80s.", "he": "להקה משנות ה-80." },
    "q-israeli_music-1448": { "en": "She sang for the troops.", "he": "היא שרה לחיילים." },
    "q-israeli_music-1449": { "en": "A famous oriental music singer.", "he": "זמר מוזיקה מזרחית מפורסם." },
    "q-israeli_music-1450": { "en": "A winner of a TV reality show.", "he": "זוכה בתוכנית ריאליטי בטלוויזיה." },
    "q-movies-1599": { "en": "A movie about a giant ape.", "he": "סרט על קוף ענק." },
    "q-movies-1600": { "en": "A film about a wizard boy.", "he": "סרט על ילד קוסם." },
    "q-movies-1601": { "en": "A movie set in space with Jedis.", "he": "סרט שמתרחש בחלל עם ג'דיי." },
    "q-movies-1602": { "en": "A story about a lion cub.", "he": "סיפור על גור אריות." },
    "q-movies-1603": { "en": "A superhero who dresses like a bat.", "he": "גיבור על שמתלבש כמו עטלף." },
    "q-movies-1604": { "en": "An archeologist with a whip.", "he": "ארכיאולוג עם שוט." },
    "q-movies-1605": { "en": "A film about a sinking ship.", "he": "סרט על ספינה טובעת." },
    "q-movies-1606": { "en": "A movie featuring a clownfish.", "he": "סרט שבו מופיע דג ליצן." },
    "q-movies-1607": { "en": "A story about toys that come to life.", "he": "סיפור על צעצועים שקמים לתחייה." },
    "q-movies-1608": { "en": "A film about a group of superheroes from Marvel.", "he": "סרט על קבוצת גיבורי על ממארוול." },
    "q-movies-1609": { "en": "An animated movie about sisters and snow.", "he": "סרט מצויר על אחיות ושלג." },
    "q-movies-1610": { "en": "A movie about a secret agent with the code 007.", "he": "סרט על סוכן חשאי עם הקוד 007." }
};

injectHints('/Users/yanivyaron/.gemini/antigravity/scratch/kids-card-game/src/data/questions/culture_ent.js', cultureBatch);
